In [1]:
#First step import usefull library

import pandas as pd
import numpy as np

## 1. Production Activities
### 1.1. For the file (Export of goods and services total and by product (2016).xlsx)

In [2]:
#Import data using pandas
pa_exports=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Production_Activities/Export of goods and services total and by product (2016).xlsx")
pa_exports

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Export of goods and services: total and by pro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Euro - Millions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Years,Products,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Total,"Products of agriculture, forestry and fishing",Mining and quarrying,"Food products, beverages and tobacco products","Textiles, wearing apparel and leather products","Wood and paper products, and printing services",Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutic...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1995,20739.8,222.2,257.7,1201.4,5170.8,1865.2,552.1,743,114.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1996,21916.8,224.5,214.4,1306.5,5428.9,1718.1,430.6,714.4,146.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1997,24341.6,289.8,240.3,1413.6,5864.1,1954.9,472.2,884.3,164.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1998,26254.6,290.2,172.6,1480.4,6038.2,2062.9,359.5,856.9,202.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1999,27488.5,299.8,166.2,1545.4,6074.8,2130.7,393.9,881.8,242.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2000,31384.6,360,183.2,1761.4,6275.2,2654.4,620.4,1174.5,324.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2001,32049.8,450.7,173.4,1799.6,6446.2,2527.6,492,1039.5,371.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2002,33406.7,488,165.9,1981.6,6237.5,2575.4,531.2,1127.5,368.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2003,35003.8,523.2,160.8,2021.5,5903.3,2628.1,648.3,1285.1,341.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2004,36837.8,592.6,266.3,2146.7,5573.3,2627.2,763.6,1545.2,340.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2005,37637.5,594.2,325.3,2341,5006,2632,1130.8,1804.8,361,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2006,44734.8,664.6,549.7,2723.1,5266,2930.7,1697.2,2033.8,400.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2007,48303.4,736.3,584.1,3206.5,5387,3090.4,1505.9,2267.1,470.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2008,49516.7,904.2,372.2,3611.1,5139,2999.8,1907.5,2196.9,487.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2009,41823.3,830,440.6,3345.7,4533.4,2652.9,1506.6,1590.7,555.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2010,47417.3,940.5,571.1,3619.7,5013.7,3202.7,2244.5,2258.3,546.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2011,53624.8,992.6,610.9,4077.3,5526.2,3389.8,2875.3,2728.4,661,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2012,56007,1041.8,706.8,4302.5,5561.8,3476.2,3614.1,2795.4,729.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2013,59478.6,1028.7,770.5,4744,5977.7,3630.7,4603.8,2975.7,730,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2014,60483.4,1146.1,695.3,4966.9,6419.3,3685.7,3712.5,2877.6,886,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2015,62636.2,1225.8,675.8,5022.9,6632.9,3920.4,3647.8,2819.7,937.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2016,63298.6,1293.7,642.1,5132.1,6984.5,3916.4,2836.4,2749.3,1102.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2017,69367.6,1418.6,654.6,5184.4,7170.8,4019.5,3587.8,3027.6,1059.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2018,73222.8,1518.4,699.4,5371.1,7158.4,4279.3,3619.6,3131,973.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2019,76167.5,1654.4,789.5,5442.3,7028.4,4314,3423.5,3341.3,1153.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Export of goods and services: total and by pro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Data Sources: INE - Annual National Accounts (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Source: PORDATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Last updated: 2021-09-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Symbology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,┴,Series break,Pro,Provisional value,Pre,Preliminary value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,...,Confidential,x,Not available,e,Less than half the unit used,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,//,Not applicable,f,Forecast,§,Extremely unreliable value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,-,Absent value,Rv,Revised value,(R),Data rectified by the relevant body,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,N,Negligible value,s,Estimated value,u,Unreliable or uncertain data,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,Data obtained in https:www.pordata.pt in 02-06...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,,,,,,,,,,,...,,,,,,,,,,

In [3]:
#Liste the name of columns
pa_exports.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       ...
       'Unnamed: 246', 'Unnamed: 247', 'Unnamed: 248', 'Unnamed: 249',
       'Unnamed: 250', 'Unnamed: 251', 'Unnamed: 252', 'Unnamed: 253',
       'Unnamed: 254', 'Unnamed: 255'],
      dtype='object', length=256)

In [4]:
#Place the name "Years" on the row that i will have the columns name, then drop the rest of columns and rows
pa_exports.loc[pa_exports.index[6], 'Unnamed: 0'] = "Years"

In [5]:
#Delete all rows with data not relevant
pa_exports = pa_exports.drop(labels=range(0, 6), axis=0)

In [6]:
#Delete all rows with data not relevant
pa_exports = pa_exports.drop(labels=range(32, 54), axis=0)

In [7]:
#Delete all columns with NAN values
pa_exports = pa_exports.dropna(thresh=10, axis=1)

In [8]:
#Rename the columns name with the values of the row index 6 
pa_exports.rename(columns=pa_exports.iloc[0], inplace = True)

In [9]:
#Rename the columns by code "Col_" plus position
pa_exports.columns = ['Col_' + str(i) if 3 <= i <= 39 else x for i, x in enumerate(pa_exports.columns, 1)]

In [10]:
#Reset index
pa_exports = pa_exports.reset_index()

In [11]:
#Delete old index
pa_exports = pa_exports.drop(labels=['index'], axis=1)

In [12]:
#Delete old columns name
pa_exports = pa_exports.drop(labels=[0], axis=0)

In [13]:
#Convert to interger and floats, because on data visualiztion verifcstion that somo tables had the data in objects
pa_exports.apply(pd.to_numeric)

,Years,Total,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10,...,Col_30,Col_31,Col_32,Col_33,Col_34,Col_35,Col_36,Col_37,Col_38,Col_39
1,1995,20739.8,222.2,257.7,1201.4,5170.8,1865.2,552.1,743.0,114.7,...,16.5,90.9,186.6,0.0,0.6,0.9,0.4,40.3,0.8,0.1
2,1996,21916.8,224.5,214.4,1306.5,5428.9,1718.1,430.6,714.4,146.3,...,13.4,78.0,156.5,0.0,0.6,0.9,0.4,33.9,0.8,0.2
3,1997,24341.6,289.8,240.3,1413.6,5864.1,1954.9,472.2,884.3,164.6,...,13.5,91.9,170.8,0.0,0.7,1.1,0.5,43.4,0.9,0.2
4,1998,26254.6,290.2,172.6,1480.4,6038.2,2062.9,359.5,856.9,202.8,...,23.1,83.3,220.8,0.1,0.9,1.5,0.6,58.5,1.2,0.2
5,1999,27488.5,299.8,166.2,1545.4,6074.8,2130.7,393.9,881.8,242.9,...,16.7,129.3,254.8,0.0,0.9,1.3,0.9,48.4,1.4,0.2
6,2000,31384.6,360.0,183.2,1761.4,6275.2,2654.4,620.4,1174.5,324.3,...,14.9,119.8,292.1,0.1,1.5,2.4,1.0,68.3,1.9,0.4
7,2001,32049.8,450.7,173.4,1799.6,6446.2,2527.6,492.0,1039.5,371.2,...,16.3,150.8,460.1,0.1,1.7,2.9,1.1,76.2,2.1,0.5
8,2002,33406.7,488.0,165.9,1981.6,6237.5,2575.4,531.2,1127.5,368.2,...,30.9,167.9,546.6,0.1,1.5,2.5,1.1,59.6,2.0,0.4
9,2003,35003.8,523.2,160.8,2021.5,5903.3,2628.1,648.3,1285.1,341.5,...,24.9,155.0,554.8,0.1,1.5,2.5,1.1,58.8,2.0,0.4
10,2004,36837.8,592.6,266.3,2146.7,5573.3,2627.2,763.6,1545.2,340.9,...,23.7,187.0,688.1,0.1,1.6,2.5,1.2,66.6,2.1,0.4
11,2005,37637.5,594.2,325.3,2341.0,5006.0,2632.0,1130.8,1804.8,361.0,...,29.1,166.1,760.1,0.1,1.2,1.8,1.0,77.0,1.7,0.3
12,2006,44734.8,664.6,549.7,2723.1,5266.0,2930.7,1697.2,2033.8,400.3,...,41.0,249.0,914.1,0.1,1.5,2.3,1.2,91.6,2.1,0.4
13,2007,48303.4,736.3,584.1,3206.5,5387.0,3090.4,1505.9,2267.1,470.1,...,89.4,360.2,1110.2,0.1,1.4,2.0,1.4,82.6,2.1,0.3
14,2008,49516.7,904.2,372.2,3611.1,5139.0,2999.8,1907.5,2196.9,487.1,...,47.0,426.2,1156.5,0.1,1.8,2.9,1.3,81.0,2.4,0.5
15,2009,41823.3,830.0,440.6,3345.7,4533.4,2652.9,1506.6,1590.7,555.8,...,57.0,474.2,1236.3,0.1,1.8,3.0,1.3,84.8,2.4,0.5
16,2010,47417.3,940.5,571.1,3619.7,5013.7,3202.7,2244.5,2258.3,546.2,...,41.9,568.9,979.6,0.1,1.7,2.8,1.2,95.7,2.2,0.4
17,2011,53624.8,992.6,610.9,4077.3,5526.2,3389.8,2875.3,2728.4,661.0,...,47.8,593.8,863.0,0.1,1.4,2.2,1.1,88.8,1.9,0.4
18,2012,56007.0,1041.8,706.8,4302.5,5561.8,3476.2,3614.1,2795.4,729.4,...,46.1,578.5,830.7,0.1,2.2,3.6,1.4,105.2,2.7,0.6
19,2013,59478.6,1028.7,770.5,4744.0,5977.7,3630.7,4603.8,2975.7,730.0,...,87.1,632.1,1218.0,0.1,51.4,57.1,0.8,123.3,2.8,0.6
20,2014,60483.4,1146.1,695.3,4966.9,6419.3,3685.7,3712.5,2877.6,886.0,...,116.8,693.2,1326.8,0.1,33.7,37.4,0.6,87.8,2.0,0.4
21,2015,62636.2,1225.8,675.8,5022.9,6632.9,3920.4,3647.8,2819.7,937.5,...,130.0,752.8,1311.6,0.1,35.8,32.7,0.5,78.3,1.7,0.4
22,2016,63298.6,1293.7,642.1,5132.1,6984.5,3916.4,2836.4,2749.3,1102.8,...,156.2,842.0,1232.8,38.0,34.6,38.9,0.4,91.9,8.0,0.3
23,2017,69367.6,1418.6,654.6,5184.4,7170.8,4019.5,3587.8,3027.6,1059.4,...,163.9,942.4,1457.6,40.6,34.8,52.4,0.5,124.3,10.3,0.4
24,2018,73222.8,1518.4,699.4,5371.1,7158.4,4279.3,3619.6,3131.0,973.8,...,194.1,963.2,1499.0,44.4,34.8,48.9,0.5,112.2,13.2,0.3
25,2019,76167.5,1654.4,789.5,5442.3,7028.4,4314.0,3423.5,3341.3,1153.9,...,228.2,993.1,1562.3,48.7,34.9,52.8,0.5,121.3,13.2,0.3

In [14]:
#Delete columns Col_39
pa_exports = pa_exports.drop(labels=['Col_39'], axis=1)

In [15]:
#Transpose
pa_exports = pa_exports.T

#Rename the columns name with the values of the row index 0 
pa_exports.rename(columns=pa_exports.iloc[0], inplace = True)

pa_exports = pa_exports.drop(labels=['Years'], axis=0)
pa_exports = pa_exports.drop(labels=['Total'], axis=0)


cols=range(1995, 2020)
pa_exports.columns=cols

In [16]:
#Export to CSV file
pa_exports.to_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Production_Activities/Export_of_goods.csv', index=True)
pa_exports

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Col_3,222.2,224.5,289.8,290.2,299.8,360,450.7,488,523.2,592.6,...,940.5,992.6,1041.8,1028.7,1146.1,1225.8,1293.7,1418.6,1518.4,1654.4
Col_4,257.7,214.4,240.3,172.6,166.2,183.2,173.4,165.9,160.8,266.3,...,571.1,610.9,706.8,770.5,695.3,675.8,642.1,654.6,699.4,789.5
Col_5,1201.4,1306.5,1413.6,1480.4,1545.4,1761.4,1799.6,1981.6,2021.5,2146.7,...,3619.7,4077.3,4302.5,4744,4966.9,5022.9,5132.1,5184.4,5371.1,5442.3
Col_6,5170.8,5428.9,5864.1,6038.2,6074.8,6275.2,6446.2,6237.5,5903.3,5573.3,...,5013.7,5526.2,5561.8,5977.7,6419.3,6632.9,6984.5,7170.8,7158.4,7028.4
Col_7,1865.2,1718.1,1954.9,2062.9,2130.7,2654.4,2527.6,2575.4,2628.1,2627.2,...,3202.7,3389.8,3476.2,3630.7,3685.7,3920.4,3916.4,4019.5,4279.3,4314
Col_8,552.1,430.6,472.2,359.5,393.9,620.4,492,531.2,648.3,763.6,...,2244.5,2875.3,3614.1,4603.8,3712.5,3647.8,2836.4,3587.8,3619.6,3423.5
Col_9,743,714.4,884.3,856.9,881.8,1174.5,1039.5,1127.5,1285.1,1545.2,...,2258.3,2728.4,2795.4,2975.7,2877.6,2819.7,2749.3,3027.6,3131,3341.3
Col_10,114.7,146.3,164.6,202.8,242.9,324.3,371.2,368.2,341.5,340.9,...,546.2,661,729.4,730,886,937.5,1102.8,1059.4,973.8,1153.9
Col_11,1101.8,1143.4,1306.4,1430.3,1520.5,1738.5,1791.5,1935.5,2137.5,2421,...,3366.9,3772.5,3974.5,4151.9,4326.4,4580.4,4581.5,4827.9,5051.6,5023.3
Col_12,872.9,950.5,1080.2,1330.9,1515.2,1894,1881.6,2238.1,3031.2,3216.2,...,3511,4258.7,4765.1,4520,4523.3,4348.1,4340.4,4893.2,5035,4898.9
Col_13,1041.3,988.1,1132.8,1368.6,1533.8,1789.1,2118.2,2030.1,2332.6,2603.4,...,1743.3,1950,1832.9,1779.4,1830,1956.7,2266.8,2777,2945.5,3445.1
Col_14,893.5,917.3,1183.3,1443.1,1367.6,1434,1292.1,1255.2,1261.4,1289.9,...,1901.2,2062.8,2259.1,2347.1,2386.7,2442.2,2358.1,2565.5,2414.1,2349
Col_15,368.7,446.6,494.1,565.7,689.6,814.1,816.7,858.6,1015.4,1177,...,1393.6,1608.3,1993.4,2113.4,2247.9,2181.3,2249.2,2368.3,2535,2234.3
Col_16,2505.3,3726.9,3880.7,4207.7,4417,4956.1,5195.7,5513.9,5431.2,5166.5,...,5289.9,6238.9,5884.8,5660.3,6005,6913.2,6922.3,7818.9,9365.8,10872.5
Col_17,576.9,598,623.8,705.1,636.9,737.7,892.7,911.2,924.8,1041.4,...,1364.7,1563.1,1565.8,1846.9,1846.8,1916.1,2031.8,2321.4,2461.9,2617.7
Col_18,1.3,2,1.4,1.9,35.3,31.1,98.5,168.6,75.8,48.4,...,72.5,88.2,26.4,131.4,158.9,114.8,262.8,303,319.4,166.1
Col_19,57.7,49.1,65.4,63.9,73.5,112.9,117.3,133.6,158,224.9,...,442.3,504.4,472,399.9,385.2,367.8,379.5,468.5,490.6,455.6
Col_20,175.1,209.8,225.1,174.9,167.6,165.4,216.2,229.4,284.3,360.9,...,520.8,587,579.2,646.8,550.2,564.7,724,777.3,796.3,769.5
Col_21,171.3,126,140,169.3,186.1,166.9,156.5,117,132.6,137.2,...,291.6,253.3,197.6,194.5,273.7,296.2,325.9,350.6,348.3,386.7
Col_22,1309.7,1280.2,1443.7,1693.7,1658.2,1918.8,2042.3,2197.6,2348.5,2517.5,...,4647.3,5199.4,5273.2,5762,5798.6,5869.6,5947.3,6885.5,7538.5,7855.5
Col_23,251.7,255.8,282,341.2,345.2,401.4,430.9,427.4,410.8,434.8,...,559.3,592,582.8,634.6,696.8,763.3,692.4,723.2,657.2,705.9
Col_24,89,84.1,113.6,118.9,123.2,168.8,176.1,163.8,165.8,202.6,...,271.3,264.2,302.1,215,261.2,244.7,252.1,231.5,216.4,237.5
Col_25,242,197.5,224,167.4,146.9,166,189.6,225.2,286.8,325.6,...,437.4,454.7,487.2,471.7,489,560.7,442.5,373.5,430.7,341.6
Col_26,38.3,31.2,38.6,46,68.3,81.9,67,80.9,95.4,115,...,271.6,369.1,460.7,514.3,609.6,735.6,887.1,1083.6,1307.5,1779.9
Col_27,453,337.3,376.9,443.7,657.1,774,351.3,352.7,335.6,414.4,...,433,449.5,580.4,509.1,462.3,504.4,502.7,527.1,598.7,652.6
Col_28,3.6,3.9,4.5,5.8,5.9,8.9,10.7,10.5,11.5,12.6,...,21.2,20.2,24.7,25.6,24.9,25,25.2,27.2,4.7,4.9
Col_29,122.5,100.5,118.4,122.6,151,169.5,192.9,269.5,251.6,299.8,...,787.3,926.5,945.9,920.4,918.8,1025.1,1006.7,1094.7,1044,1168.4
Col_30,16.5,13.4,13.5,23.1,16.7,14.9,16.3,30.9,24.9,23.7,...,41.9,47.8,46.1,87.1,116.8,130,156.2,163.9,194.1,228.2
Col_31,90.9,78,91.9,83.3,129.3,119.8,150.8,167.9,155,187,...,568.9,593.8,578.5,632.1,693.2,752.8,842,942.4,963.2,993.1
Col_32,186.6,156.5,170.8,220.8,254.8,292.1,460.1,546.6,554.8,688.1,...,979.6,863,830.7,1218,1326.8,1311.6,1232.8,1457.6,1499,1562.3
Col_33,0,0,0,0.1,0,0.1,0.1,0.1,0.1,0.1,...,0.1,0.1,0.1,0.1,0.1,0.1,38,40.6,44.4,48.7
Col_34,0.6,0.6,0.7,0.9,0.9,1.5,1.7,1.5,1.5,1.6,...,1.7,1.4,2.2,51.4,33.7,35.8,34.6,34.8,34.8,34.9
Col_35,0.9,0.9,1.1,1.5,1.3,2.4,2.9,2.5,2.5,2.5,...,2.8,2.2,3.6,57.1,37.4,32.7,38.9,52.4,48.9,52.8
Col_36,0.4,0.4,0.5,0.6,0.9,1,1.1,1.1,1.1,1.2,...,1.2,1.1,1.4,0.8,0.6,0.5,0.4,0.5,0.5,0.5
Col_37,40.3,33.9,43.4,58.5,48.4,68.3,76.2,59.6,58.8,66.6,...,95.7,88.8,105.2,123.3,87.8,78.3,91.9,124.3,112.2,121.3
Col_38,0.8,0.8,0.9,1.2,1.4,1.9,2.1,2,2,2.1,...,2.2,1.9,2.7,2.8,2,1.7,8,10.3,13.2,13.2

### 1.2. For the file (Import of goods and services total and by product (2016).xlsx)

In [17]:
#Import data using pandas
pa_imports=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Production_Activities/Import of goods and services total and by product (2016).xlsx")

In [18]:
#Place the name "Years" on the row that i will have the columns name, then drop the rest of columns and rows
pa_imports.loc[pa_imports.index[6], 'Unnamed: 0'] = "Years"

In [19]:
#Delete all rows with data not relevant
pa_imports = pa_imports.drop(labels=range(0, 6), axis=0)

In [20]:
#Delete all rows with data not relevant
pa_imports = pa_imports.drop(labels=range(32, 54), axis=0)

In [21]:
#Delete all columns with NAN values
pa_imports = pa_imports.dropna(thresh=10, axis=1)

In [22]:
#Rename the columns name with the values of the row index 6 
pa_imports.rename(columns=pa_imports.iloc[0], inplace = True)

In [23]:
#Rename the columns by code "Col_" plus position
pa_imports.columns = ['Col_' + str(i) if 3 <= i <= 39 else x for i, x in enumerate(pa_imports.columns, 1)]

In [24]:
#Reset index
pa_imports = pa_imports.reset_index()

In [25]:
#Delete old index
pa_imports = pa_imports.drop(labels=['index'], axis=1)

In [26]:
#Delete old columns name
pa_imports = pa_imports.drop(labels=[0], axis=0)

In [27]:
#Convert to interger and floats, because on data visualiztion verifation that some tables had the data in objects
pa_imports.apply(pd.to_numeric)

,Years,Total,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10,...,Col_30,Col_31,Col_32,Col_33,Col_34,Col_35,Col_36,Col_37,Col_38,Col_39
1,1995,28397.0,1765.1,1536.7,2404.8,2286.4,788.4,642.9,2219.9,551.9,...,24.8,172.9,448.7,0.1,3.1,3.1,0.8,47.6,2.0,0.5
2,1996,30524.0,1873.4,1547.1,2583.5,2478.3,839.4,675.6,2283.8,634.4,...,22.2,150.1,395.1,0.1,3.6,3.6,0.9,45.5,2.3,0.6
3,1997,34732.1,1956.9,1876.3,2750.5,2816.8,946.4,698.5,2567.6,716.3,...,17.4,204.7,495.9,0.1,3.4,4.1,1.0,55.5,2.4,0.7
4,1998,39234.4,2205.6,1426.1,3194.5,3181.9,1108.3,634.1,2761.5,806.2,...,22.0,309.0,588.8,0.1,3.8,3.8,1.0,81.9,2.4,0.6
5,1999,42675.7,2017.5,1987.5,3521.7,3200.8,1216.4,773.6,2810.0,1041.7,...,22.2,243.5,589.1,0.2,3.8,4.6,1.1,72.4,2.8,0.7
6,2000,48851.4,2183.6,3298.9,3645.0,3606.7,1449.2,1381.5,3207.1,1100.6,...,31.5,236.0,560.5,0.2,4.1,5.1,1.2,83.6,3.0,0.8
7,2001,49644.6,2375.2,3239.3,3904.3,3800.6,1510.6,1337.1,3286.0,1301.5,...,25.9,175.8,592.3,0.1,3.2,3.9,1.0,83.3,2.3,0.6
8,2002,48849.2,2299.8,2946.7,3911.4,3761.2,1503.9,1387.9,3412.7,1480.7,...,27.7,178.9,724.6,0.1,2.5,2.8,0.7,79.6,1.7,0.5
9,2003,48056.4,2183.4,3154.4,3942.0,3608.9,1460.4,1254.4,3444.7,1561.8,...,40.2,173.3,666.1,0.1,2.4,2.7,0.7,70.9,1.6,0.4
10,2004,52786.5,2263.8,3852.9,4166.6,3645.2,1539.4,1306.5,3727.0,1758.3,...,33.9,164.7,652.8,0.1,2.2,2.6,0.7,94.3,1.6,0.4
11,2005,55379.3,2215.9,5112.0,4187.6,3398.1,1556.5,1939.2,3960.5,1782.9,...,49.7,168.3,714.3,0.1,2.1,2.7,0.7,142.1,1.6,0.4
12,2006,61897.0,2325.9,6239.1,4730.2,3766.1,1659.4,1975.2,4404.8,2035.6,...,44.3,246.0,765.2,0.1,3.4,3.9,1.0,178.7,2.4,0.6
13,2007,66282.2,2838.7,5818.7,5144.7,3988.1,1813.3,2208.1,4665.6,2066.5,...,58.9,236.8,980.0,0.1,3.2,3.5,0.9,157.4,2.1,0.6
14,2008,71289.9,3127.4,7673.9,5596.4,3931.9,1797.3,2643.1,4728.3,2182.7,...,80.4,287.8,1091.2,0.1,2.5,2.7,0.7,169.9,1.8,0.4
15,2009,58277.0,2604.2,4775.5,5334.3,3676.5,1580.1,1897.1,4069.7,2358.9,...,59.4,295.9,1259.9,0.1,1.9,2.4,0.6,161.2,1.3,0.4
16,2010,65946.7,2972.0,6461.3,5610.7,4159.6,1743.6,2240.3,5161.4,2359.5,...,71.9,391.1,1394.6,0.1,1.4,1.8,0.4,145.9,0.9,0.3
17,2011,66280.4,3248.8,7799.3,6078.3,4148.1,1737.1,3003.3,5631.3,2292.0,...,70.4,378.4,1118.7,0.1,1.1,1.5,0.4,137.2,0.7,0.3
18,2012,62498.9,3167.9,9230.3,5881.3,3816.4,1552.8,2644.3,5662.5,2226.1,...,55.4,356.0,994.8,0.1,1.3,1.8,0.4,155.7,0.9,0.3
19,2013,63795.6,3285.9,8721.0,6130.6,4218.3,1585.4,2707.4,5620.0,2108.6,...,99.9,419.6,1003.6,0.1,56.9,73.1,0.3,166.2,0.9,0.2
20,2014,67302.5,3144.1,7676.3,6099.0,4631.0,1703.8,3151.2,5769.0,2196.2,...,142.7,560.1,1489.1,0.1,20.9,27.4,0.4,64.4,0.9,0.3
21,2015,69483.3,3347.7,6457.9,6326.8,4941.4,1776.2,2274.5,5967.3,2391.3,...,146.7,624.3,1504.1,0.1,23.3,31.8,0.7,65.5,1.4,0.5
22,2016,70332.2,3465.1,5145.5,6558.3,5114.0,1843.2,1884.6,5969.4,2465.5,...,191.2,738.6,1936.8,0.1,22.7,32.3,0.4,72.2,0.9,0.3
23,2017,78862.0,3626.7,6665.5,6958.0,5345.7,1970.6,2368.1,6719.7,2464.2,...,175.2,821.7,1947.1,0.1,22.8,31.1,0.4,70.3,0.9,0.3
24,2018,84973.9,3829.0,7310.0,7239.2,5404.2,2129.1,2695.2,7351.6,2617.8,...,228.7,838.9,1917.4,0.1,23.1,33.9,0.5,83.6,1.1,0.3
25,2019,88660.3,3789.0,6567.5,7506.2,5545.8,2161.2,3202.7,7657.0,2752.3,...,187.0,851.4,2357.7,0.1,23.0,41.8,0.5,101.2,1.1,0.3

In [28]:
#Delete columns Col_39
pa_imports = pa_imports.drop(labels=['Col_39'], axis=1)

In [29]:
#Transpose
pa_imports = pa_imports.T

#Rename the columns name with the values of the row index 0 
pa_imports.rename(columns=pa_imports.iloc[0], inplace = True)

pa_imports = pa_imports.drop(labels=['Years'], axis=0)
pa_imports = pa_imports.drop(labels=['Total'], axis=0)


cols=range(1995, 2020)
pa_imports.columns=cols

In [30]:
#Export to CSV file
pa_imports.to_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Production_Activities/Import_of_goods.csv', index=True)
pa_imports

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Col_3,1765.1,1873.4,1956.9,2205.6,2017.5,2183.6,2375.2,2299.8,2183.4,2263.8,...,2972,3248.8,3167.9,3285.9,3144.1,3347.7,3465.1,3626.7,3829,3789
Col_4,1536.7,1547.1,1876.3,1426.1,1987.5,3298.9,3239.3,2946.7,3154.4,3852.9,...,6461.3,7799.3,9230.3,8721,7676.3,6457.9,5145.5,6665.5,7310,6567.5
Col_5,2404.8,2583.5,2750.5,3194.5,3521.7,3645,3904.3,3911.4,3942,4166.6,...,5610.7,6078.3,5881.3,6130.6,6099,6326.8,6558.3,6958,7239.2,7506.2
Col_6,2286.4,2478.3,2816.8,3181.9,3200.8,3606.7,3800.6,3761.2,3608.9,3645.2,...,4159.6,4148.1,3816.4,4218.3,4631,4941.4,5114,5345.7,5404.2,5545.8
Col_7,788.4,839.4,946.4,1108.3,1216.4,1449.2,1510.6,1503.9,1460.4,1539.4,...,1743.6,1737.1,1552.8,1585.4,1703.8,1776.2,1843.2,1970.6,2129.1,2161.2
Col_8,642.9,675.6,698.5,634.1,773.6,1381.5,1337.1,1387.9,1254.4,1306.5,...,2240.3,3003.3,2644.3,2707.4,3151.2,2274.5,1884.6,2368.1,2695.2,3202.7
Col_9,2219.9,2283.8,2567.6,2761.5,2810,3207.1,3286,3412.7,3444.7,3727,...,5161.4,5631.3,5662.5,5620,5769,5967.3,5969.4,6719.7,7351.6,7657
Col_10,551.9,634.4,716.3,806.2,1041.7,1100.6,1301.5,1480.7,1561.8,1758.3,...,2359.5,2292,2226.1,2108.6,2196.2,2391.3,2465.5,2464.2,2617.8,2752.3
Col_11,1071.7,1253,1478,1688,1836,2066.3,2139.8,2216.3,2128.5,2210.3,...,2449.8,2433.8,2188.3,2264.5,2435.4,2601.6,2752.8,3049.2,3363.3,3591
Col_12,2153.2,2061.4,2450.3,2780.4,2952.4,3647.3,3634.5,3624.6,3643.7,4375.2,...,4643.1,4591.3,4012.4,4068.2,4192.8,4441.9,4350.5,5231.8,5644.4,5623.9
Col_13,2071.7,2188.4,2532.7,3370,3700.9,4248.3,4519.4,4264.5,4342.5,4881.5,...,4074.6,3662.7,3457,3385,3574.7,3886.1,4134.6,4742,5083.3,5718.8
Col_14,1258.6,1410.7,1643,1835.7,1854.3,2095.4,2034,1982.4,1916.9,2018.9,...,2410.3,2309.8,2022.6,2060.3,2148.2,2247.4,2461.9,2789.5,3091.2,3243.1
Col_15,1890,2232.7,2597.7,2967.9,3179.4,3575.6,3484.2,3097.4,2907.5,3293.2,...,3485.1,3176.1,2799.3,3001.9,3384.9,3537,3740.9,4333.8,4761.2,4801.3
Col_16,3922.9,4682.2,5503.1,6586,7698.7,8018.4,7754.3,7182.3,6652.6,7260.5,...,8705.8,6987.8,5209.8,5628.5,6787,8223.5,8924.8,10115.3,11200.6,11850
Col_17,659.6,760.7,855.2,1012,1130.6,1255.9,1351.7,1442.6,1430,1553.1,...,2031.3,1968.1,1608.1,1673.8,1799.2,1979.6,2161.7,2404.4,2507.5,2747.7
Col_18,15.1,27,55.7,16,20.9,43.6,114.2,187.1,204,374.2,...,177.6,228.3,397.7,259.1,200.3,238.4,90.2,169.5,176.8,344.9
Col_19,41.4,28,31.9,44.3,52.1,63.2,53.7,70.3,95.1,195.2,...,337.3,494,465.9,490.3,505.6,445.9,397.8,520.5,616.2,490.5
Col_20,185.4,186.3,147.8,102,125.4,68.9,91.1,120.3,143.9,131.3,...,96.6,117.9,104.2,119.3,102.8,100.3,124.9,129.2,135.4,278.1
Col_21,159.8,149.9,133.9,126.7,170.2,169.9,156.1,140.8,140.9,186.1,...,244,209.1,232.2,174.4,254.9,261.8,357.4,445.9,518.8,610.4
Col_22,472.8,487.1,544,598,661.4,797.1,823.1,810.8,808.1,823.5,...,1234.5,1233.6,1313.7,1612,1979.7,2048.7,1935.2,2221.2,2350.3,2525.6
Col_23,198.3,231.4,245.4,292.7,309.6,366.2,365.7,359.2,355.3,384.7,...,557.4,559.5,476.3,501.1,534,586,582.8,668.6,750.1,837.1
Col_24,375.4,359.6,407,481.3,525.3,598.7,637.3,583.9,607.7,655.4,...,661,619.8,571,517.4,566.4,613.2,669.8,590.3,636.3,637.9
Col_25,147.2,130.3,149.4,146.4,116.6,161.8,172.4,199.1,214.4,265.4,...,408.6,407.7,400.7,392.6,445.3,531.3,373.5,348.7,309.4,268.6
Col_26,103.6,91.1,98.7,132.2,185,177.4,170.9,204.7,203.2,170.8,...,369.6,440.4,368.3,423.7,533.6,534.5,591,592.7,734.6,806.4
Col_27,531.5,488.8,481.1,388,377.7,437.3,284.1,426.4,476,559.9,...,957.5,854.1,787.6,690.5,730.6,758,732.2,715.8,750.2,899.3
Col_28,9.8,11.4,12.8,11.9,14.6,16,12.3,9,8.4,8.3,...,12.4,9.1,9.8,7.4,10.9,18,11.3,11.2,13.7,13
Col_29,229.3,204.6,250.1,323.1,255.1,245.5,202.8,203.8,209.1,225.9,...,373.5,330.4,325.9,327.6,439.1,548.6,497.6,594,626.9,627.2
Col_30,24.8,22.2,17.4,22,22.2,31.5,25.9,27.7,40.2,33.9,...,71.9,70.4,55.4,99.9,142.7,146.7,191.2,175.2,228.7,187
Col_31,172.9,150.1,204.7,309,243.5,236,175.8,178.9,173.3,164.7,...,391.1,378.4,356,419.6,560.1,624.3,738.6,821.7,838.9,851.4
Col_32,448.7,395.1,495.9,588.8,589.1,560.5,592.3,724.6,666.1,652.8,...,1394.6,1118.7,994.8,1003.6,1489.1,1504.1,1936.8,1947.1,1917.4,2357.7
Col_33,0.1,0.1,0.1,0.1,0.2,0.2,0.1,0.1,0.1,0.1,...,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1
Col_34,3.1,3.6,3.4,3.8,3.8,4.1,3.2,2.5,2.4,2.2,...,1.4,1.1,1.3,56.9,20.9,23.3,22.7,22.8,23.1,23
Col_35,3.1,3.6,4.1,3.8,4.6,5.1,3.9,2.8,2.7,2.6,...,1.8,1.5,1.8,73.1,27.4,31.8,32.3,31.1,33.9,41.8
Col_36,0.8,0.9,1,1,1.1,1.2,1,0.7,0.7,0.7,...,0.4,0.4,0.4,0.3,0.4,0.7,0.4,0.4,0.5,0.5
Col_37,47.6,45.5,55.5,81.9,72.4,83.6,83.3,79.6,70.9,94.3,...,145.9,137.2,155.7,166.2,64.4,65.5,72.2,70.3,83.6,101.2
Col_38,2,2.3,2.4,2.4,2.8,3,2.3,1.7,1.6,1.6,...,0.9,0.7,0.9,0.9,0.9,1.4,0.9,0.9,1.1,1.1

### 1.3. For the file (Gross value of production total and by industry (2016).xlsx)

In [31]:
#Import data using pandas
pa_production=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Production_Activities/Gross value of production total and by industry (2016).xlsx")
pa_production

,Years,Total,"Agriculture, forestry and fishing",Mining and quarrying,"Manufacture of food products, beverages and tobacco products","Manufacture of textiles, wearing apparel and leather products","Manufacture of wood and paper products, and printing",Manufacture of coke and refined petroleum products,Manufacture of chemicals and chemical products,Manufacture of basic pharmaceutical products and pharmaceutical preparations,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,1995,171311.82,6847.59,910.94,10031.24,10628.82,5614.63,1783.91,2402.02,759.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996,182948.79,7198.9,859.1,10748.17,10987.72,5447.41,1874.33,2423.87,773.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997,198180.46,6751.11,982.19,10753.41,11545.8,5851.89,2191.4,2735.58,865.23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998,212920.6,6832.91,1012.77,11135.14,11644.88,6371.3,1777.1,2625.53,817.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1999,224592.74,6978.79,1030.33,11418.83,11320.01,6511.54,2188.51,2539.32,791.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,245157.91,7093.7,1119.5,11846.41,11635.3,7423.9,3511.26,2838.52,874.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2001,259028.36,7308.38,1193.54,12574.69,11827.12,7342.03,3359,2801.09,908.78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2002,265101.43,7169.71,1118.04,12524.19,11523.3,7126.55,3052.48,2837.32,939.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2003,268623.87,7177.79,1049.22,12527.63,11007.41,7125.46,3272.6,2964.42,879.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2004,282392.65,7434.19,1163.81,12975.57,10654.22,7136.75,4023.12,3311.34,919.67,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2005,293681.92,7153.66,1289.69,13071.3,9751.27,7239.76,5623.34,3456.4,938.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2006,305830.4,7291.01,1468.89,13469.95,9771.39,7549.37,6814.8,3715.75,978.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2007,324450.51,7511.24,1558.63,14393.63,9879.67,7943.55,6622.34,4122.33,1130.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2008,337724.4,7799.19,1387.14,15578.66,9155.17,7650.86,8153.56,4053.09,1092.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2009,318276.02,7328.78,1238.76,14741.21,8101.25,6469.07,4841.13,3120.87,1125.16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,328296.2,7582.7,1360.19,14811.45,8682.22,7337.88,6861.79,4210.9,1114.65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2011,326710.76,7743.22,1334.89,15364.13,9013.5,7585.54,8206.3,4657.67,1149.54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2012,309317.61,7892.78,1276.97,15549.02,8922.39,7457.43,9051.29,4677.58,1120.32,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2013,307542.76,8082.26,1162.38,15906.57,9497.89,7419.04,9397.53,4603.95,1121.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2014,309830.68,8151.05,1113.08,15959.78,10055.9,7626.77,8386.71,4413.25,1041.64,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,317832.82,8407.55,1116.42,16150.93,10505.81,8098.4,7072.78,4356.48,1175.93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2016,324823.38,8464.06,1121.12,16471.81,10872.09,8032.36,5762.05,4125.88,1148.86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2017,347793.26,8951.77,1245.55,17302.91,11170.69,8481.95,7138.11,4703.46,1265.39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2018,366734.44,9239.27,1356.56,17653.6,11271.35,9339.71,7792.16,4824.02,1373.51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2019,381406.57,9670.72,1326.01,18026.28,10883.32,9298.51,7328.85,4961.79,1440.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2020,352950.49,9413.6,1279.06,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Gross value of production: total and by indust...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Data Sources: INE - Annual National Accounts (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Source: PORDATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Last updated: 2021-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Symbology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,┴,Series break,Pro,Provisional value,Pre,Preliminary value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,...,Confidential,x,Not available,e,Less than half the unit used,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,//,Not applicable,f,Forecast,§,Extremely unreliable value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,-,Absent value,Rv,Revised value,(R),Data rectified by the relevant body,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,N,Negligible value,s,Estimated value,u,Unreliable or uncertain data,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Data obtained in https:www.pordata.pt in 02-06...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,,,,,,,,,,,...,,,,,,,,,,

In [32]:
#Liste the name of columns
pa_production.columns

Index(['Years', 'Total', 'Agriculture, forestry and fishing',
       'Mining and quarrying',
       'Manufacture of food products, beverages and tobacco products',
       'Manufacture of textiles, wearing apparel and leather products',
       'Manufacture of wood and paper products, and printing',
       'Manufacture of coke and refined petroleum products',
       'Manufacture of chemicals and chemical products',
       'Manufacture of basic pharmaceutical products and pharmaceutical preparations',
       ...
       'Unnamed: 246', 'Unnamed: 247', 'Unnamed: 248', 'Unnamed: 249',
       'Unnamed: 250', 'Unnamed: 251', 'Unnamed: 252', 'Unnamed: 253',
       'Unnamed: 254', 'Unnamed: 255'],
      dtype='object', length=256)

In [33]:
#Delete all rows with data not relevant
pa_production = pa_production.drop(labels=range(25, 48), axis=0)

In [34]:
#Delete all columns with NAN values
pa_production = pa_production.dropna(thresh=10, axis=1)

In [35]:
#Change the types of data have  to be used in visulizations and database
pa_production = pa_production.astype(float)
pa_production['Years'] = pa_production['Years'].astype(int)

In [36]:
#Verify that the types of data have changed to be used in visulizations and database
pa_production.dtypes

Years                                                                                                                                                                         int64
Total                                                                                                                                                                       float64
Agriculture, forestry and fishing                                                                                                                                           float64
Mining and quarrying                                                                                                                                                        float64
Manufacture of food products, beverages and tobacco products                                                                                                                float64
Manufacture of textiles, wearing apparel and leather products                                                                                                               float64
Manufacture of wood and paper products, and printing                                                                                                                        float64
Manufacture of coke and refined petroleum products                                                                                                                          float64
Manufacture of chemicals and chemical products                                                                                                                              float64
Manufacture of basic pharmaceutical products and pharmaceutical preparations                                                                                                float64
Manufacture of rubber and plastic products, and other non-metallic mineral products                                                                                         float64
Manufacture of basic metals and fabricated metal products, except machinery and equipment                                                                                   float64
Manufacture of computer, electronic and optical products                                                                                                                    float64
Manufacture of electrical equipment                                                                                                                                         float64
Manufacture of machinery and equipment n.e.c.                                                                                                                               float64
Manufacture of transport equipment                                                                                                                                          float64
Manufacture of furniture, other manufacturing, repair and installation of machinery and equipment                                                                           float64
Electricity, gas, steam and air-conditioning supply                                                                                                                         float64
Water supply, sewerage, waste management and remediation activities                                                                                                         float64
Construction                                                                                                                                                                float64
Wholesale and retail trade, repair of motor vehicles and motorcycles                                                                                                        float64
Transportation and storage                                                                                                                                                  float64
Accommodation and food service activities                                                                                                                                   float64
Publishing, audiovisual and broadcasting activities                                                                                                                         float64
Telecommunications                                                                                                                                                          float64
Computer programming, consultancy and related activities, information service activities                                                                                    float64
Financial and insurance activities                                                                                                                                          float64
Real estate activities                                                                                                                                                      float64
Legal and accounting activities, activities of head offices, management consultancy activities, architectural and engineering activities, technical testing and analysis    float64
Scientific research and development                                                                                                                                         float64
Advertising and market research, other professional, scientific and technical activities, veterinary activities                                                             float64
Administrative and support service activities                                                                                                                               float64
Public administration and defence, compulsory social security                                                                                                               float64
Education                                                                                                                                                                   float64
Human health activities                                                                                                                                                     float64
Social work activities                                                                                                                                                      float64
Arts, entertainment and recreation                                                                                                                                          float64
Other service activities                                                                                                                                                    float64
Activities of households as employers of domestic personnel and undifferentiated goods and services production of households for own use                                    float64
dtype: object

In [37]:
#Rename the columns by code "Col_" plus position
pa_production.columns = ['Col_' + str(i) if 3 <= i <= 39 else x for i, x in enumerate(pa_production.columns, 1)]

In [38]:
#Delete columns Col_39
pa_production = pa_production.drop(labels=['Col_39'], axis=1)

In [39]:
#Transpose
pa_production = pa_production.T


#Rename the columns name with the values of the row index 0 
pa_production.rename(columns=pa_production.iloc[0], inplace = True)

pa_production = pa_production.drop(labels=['Years'], axis=0)
pa_production = pa_production.drop(labels=['Total'], axis=0)


cols=range(1995, 2020)
pa_production.columns=cols

In [40]:
#Export to CSV file
pa_production.to_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Production_Activities/Production_of_goods.csv', index=True)
pa_production

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Col_3,6847.59,7198.90,6751.11,6832.91,6978.79,7093.70,7308.38,7169.71,7177.79,7434.19,...,7582.70,7743.22,7892.78,8082.26,8151.05,8407.55,8464.06,8951.77,9239.27,9670.72
Col_4,910.94,859.10,982.19,1012.77,1030.33,1119.50,1193.54,1118.04,1049.22,1163.81,...,1360.19,1334.89,1276.97,1162.38,1113.08,1116.42,1121.12,1245.55,1356.56,1326.01
Col_5,10031.24,10748.17,10753.41,11135.14,11418.83,11846.41,12574.69,12524.19,12527.63,12975.57,...,14811.45,15364.13,15549.02,15906.57,15959.78,16150.93,16471.81,17302.91,17653.60,18026.28
Col_6,10628.82,10987.72,11545.80,11644.88,11320.01,11635.30,11827.12,11523.30,11007.41,10654.22,...,8682.22,9013.50,8922.39,9497.89,10055.90,10505.81,10872.09,11170.69,11271.35,10883.32
Col_7,5614.63,5447.41,5851.89,6371.30,6511.54,7423.90,7342.03,7126.55,7125.46,7136.75,...,7337.88,7585.54,7457.43,7419.04,7626.77,8098.40,8032.36,8481.95,9339.71,9298.51
Col_8,1783.91,1874.33,2191.40,1777.10,2188.51,3511.26,3359.00,3052.48,3272.60,4023.12,...,6861.79,8206.30,9051.29,9397.53,8386.71,7072.78,5762.05,7138.11,7792.16,7328.85
Col_9,2402.02,2423.87,2735.58,2625.53,2539.32,2838.52,2801.09,2837.32,2964.42,3311.34,...,4210.90,4657.67,4677.58,4603.95,4413.25,4356.48,4125.88,4703.46,4824.02,4961.79
Col_10,759.75,773.09,865.23,817.97,791.29,874.61,908.78,939.01,879.94,919.67,...,1114.65,1149.54,1120.32,1121.03,1041.64,1175.93,1148.86,1265.39,1373.51,1440.43
Col_11,4798.33,4998.57,5542.54,5908.11,6203.89,6675.75,6913.00,6996.52,6840.95,7111.61,...,7378.08,7498.64,6957.43,6811.96,7066.36,7471.48,7512.50,8191.69,8693.67,8974.46
Col_12,4323.81,4244.01,4787.66,5189.61,5345.84,5986.87,6136.96,6228.70,6353.30,7102.66,...,7889.10,8293.63,7861.74,7736.45,8018.29,8084.42,8259.59,9419.20,10179.06,10024.42
Col_13,1803.70,1884.99,2027.58,2143.31,2349.28,2588.89,2562.39,2639.69,2714.15,2737.37,...,1914.75,1939.55,1749.54,1582.93,1527.79,1695.24,1959.07,2389.81,2566.91,2589.07
Col_14,1354.52,1413.14,1525.30,1626.78,1778.15,1923.98,1969.87,1888.31,1768.45,1741.26,...,2552.46,2538.54,2329.21,2440.95,2445.72,2521.15,2460.48,2711.68,2684.38,2625.92
Col_15,1397.92,1503.84,1673.44,1825.21,1992.52,2196.05,2240.37,2308.63,2293.27,2372.50,...,2404.50,2301.47,2177.07,2285.91,2593.84,2475.95,2618.26,2716.47,2841.30,2760.21
Col_16,4658.22,6185.65,6792.41,7058.69,6900.52,7272.92,7347.55,7358.68,7074.18,6812.70,...,6634.70,7734.62,7158.65,6948.91,7341.09,8261.54,8563.42,10023.84,11873.36,12813.39
Col_17,2383.80,2670.46,2893.34,3117.37,3244.17,3441.76,3592.89,3630.61,3665.61,3718.55,...,4350.85,4174.23,3921.13,3901.91,4056.89,4359.12,4430.86,4893.15,5297.35,5489.81
Col_18,4605.85,4556.99,4598.60,5075.21,5559.80,6109.07,6670.96,6954.01,7362.27,7972.09,...,12625.26,13514.24,14410.29,14293.65,13989.06,14699.92,14981.63,15666.25,16154.34,15668.70
Col_19,1223.88,1333.03,1454.69,1605.57,1780.20,1998.68,2117.85,2279.96,2537.93,2757.61,...,4065.45,4291.60,4150.36,4002.05,3875.74,3997.69,3986.92,4307.54,4349.98,4483.90
Col_20,17475.79,19177.06,22632.80,25066.21,26492.05,29167.30,31395.12,32308.09,30887.40,32689.69,...,30333.25,27103.60,20763.05,18284.04,16877.97,17014.47,16806.47,18769.67,20685.27,22792.26
Col_21,21364.42,22794.43,24441.53,26548.17,27680.74,29582.44,31207.02,31960.28,32172.43,33850.70,...,37217.61,36347.07,35064.91,34955.19,36113.57,37388.99,38451.24,39730.65,40690.67,42217.98
Col_22,6250.05,6961.87,7716.31,8597.72,9171.94,10365.92,11019.40,11461.15,12084.71,13034.01,...,18151.62,18436.97,17464.21,17672.27,17875.14,19507.49,19753.88,21338.94,22451.48,23809.13
Col_23,6867.68,7250.29,7826.84,8619.25,8994.16,9743.80,10421.30,10901.04,10976.82,11672.40,...,13979.71,13793.37,13264.35,13188.89,13949.31,14789.65,15837.30,17895.96,19261.08,20548.32
Col_24,1883.58,1896.48,2057.59,2171.22,2305.20,2614.01,2598.82,2531.49,2559.71,2712.99,...,2965.19,2736.75,2409.79,2273.52,2326.93,2374.01,2428.49,2510.94,2542.92,2631.83
Col_25,3474.24,3854.70,4224.01,4632.90,4912.14,5550.28,6682.15,6772.17,6886.37,7223.52,...,7433.12,6671.49,6444.83,6036.70,5497.71,5440.28,5644.46,5664.71,5430.24,5575.62
Col_26,1092.40,1200.89,1313.95,1445.87,1602.43,1733.79,1821.75,2008.64,2119.08,2221.17,...,3203.27,3281.31,3299.85,3374.22,3561.97,3681.57,3975.50,4520.89,5193.36,6284.33
Col_27,6472.78,6668.68,7676.10,8776.85,9690.85,10299.96,11777.69,12142.42,12676.58,13473.53,...,17156.52,17535.56,16172.84,15304.65,14713.92,14760.01,14664.08,14547.60,15088.13,15471.49
Col_28,7797.33,8399.92,9002.49,9770.86,10570.66,11343.25,12174.47,13101.36,13866.11,14479.15,...,19529.97,19408.86,19243.19,19921.13,20770.90,21500.48,22892.77,24378.77,25563.05,27082.93
Col_29,3945.53,4280.34,4617.59,5151.82,5711.46,6193.42,6576.34,6638.33,6936.81,7169.91,...,8975.43,8804.88,8258.55,8069.30,8637.49,8759.44,8995.44,9701.36,10601.63,11392.24
Col_30,181.66,200.27,216.41,240.07,267.10,278.87,310.70,339.47,353.26,397.35,...,685.03,661.29,662.50,704.72,805.09,811.09,850.45,850.71,905.03,994.41
Col_31,1552.09,1669.26,1816.96,1997.86,2189.07,2383.45,2452.09,2229.30,2321.78,2546.80,...,2830.21,2664.20,2304.75,2265.14,2407.06,2541.56,2717.12,2958.48,3200.67,3461.36
Col_32,3604.05,3961.07,4330.73,4739.44,5167.01,5622.23,5740.52,6010.41,6211.26,6559.98,...,8855.74,8529.80,7912.54,7868.92,8205.93,8656.34,9379.76,10498.94,11380.52,11971.75
Col_33,8124.04,8682.87,9332.83,10267.69,11068.80,12653.48,13080.87,13511.70,14245.14,14800.58,...,17956.96,17250.05,15994.57,16732.38,16389.17,15399.45,15544.16,15863.52,16305.78,16784.80
Col_34,5906.49,6206.55,6765.69,7253.37,7838.88,8682.95,9312.04,10055.50,10359.99,10844.44,...,12870.27,12043.94,10600.96,10977.25,10807.94,10708.50,10910.43,11285.72,11705.80,12126.65
Col_35,4670.90,5056.19,5417.26,5884.29,6634.26,7325.27,8112.57,8744.54,9374.61,10212.54,...,13224.04,13045.95,12019.53,12069.35,12347.76,12791.78,13380.75,14033.78,14872.78,15850.82
Col_36,1664.42,1779.89,1810.87,1862.87,1956.40,2140.00,2367.26,2490.83,2481.00,2688.38,...,3485.57,3663.83,3669.37,3751.29,3749.32,3876.76,4186.11,4542.92,4670.93,4783.89
Col_37,1376.84,1493.52,1566.91,1613.90,1757.51,1992.93,2061.90,2034.29,1991.71,2188.29,...,2727.38,2602.66,2376.19,2249.38,2451.24,2654.40,2859.77,3170.52,3440.54,3838.07
Col_38,1584.16,1742.85,1808.25,1867.14,1971.28,2220.77,2282.85,2446.54,2627.15,2798.65,...,3706.38,3587.36,3577.93,3543.05,3566.62,3640.59,3677.50,3835.73,4095.43,4192.83

## 2. Efficiency and Return
### 2.1. For the file (Apparent labour productivity total and by industry.xlsx)

In [41]:
#Import data using pandas
ef_productivity=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Efficiency_and _Return/Apparent labour productivity total and by industry.xlsx")
ef_productivity

,Years,Total,"Agriculture, forestry and fishing",Mining and quarrying,"Manufacture of food products, beverages and tobacco products","Manufacture of textiles, wearing apparel and leather products","Manufacture of wood and paper products, and printing",Manufacture of coke and refined petroleum products,Manufacture of chemicals and chemical products,Manufacture of basic pharmaceutical products and pharmaceutical preparations,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,1995,18176.07,9161.38,34275.96,13823.52,9446.11,18950.96,27285.81,39621.88,39943.85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996,18880.6,9159.26,30249.94,15590.86,10226.27,18178.73,41255.79,41379.97,41651.83,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997,19963.27,8239.76,32103.77,16629.32,10434.46,19732.4,58558.36,44715.01,44983.36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998,20871.56,8605.59,33141.17,18311.62,10345.16,20836.64,96756.29,41166.52,42844.63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1999,21990.33,8902.29,32997.47,20902.23,10726.39,21764.65,61307.9,39271.06,41121.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,23133.1,8809.1,33664.85,20071,10623.54,25647.79,83195.16,41428.41,44979.57,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2001,24183.21,8842.2,34895.48,22226.07,10966.11,25203.06,86683.1,42311.71,52361.91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2002,25230.05,8967.58,31143.81,24584.47,11785.4,25297.29,72880.59,42265.63,55726.95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2003,26174.16,9018.98,30072.39,25985.42,12275.85,24996.96,83605.85,43359.51,57666.51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2004,27474.36,9753.43,35695.46,27291.87,12372.61,25206.05,154551.52,48517.71,62245.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2005,28474.63,9223.44,39117.72,28182.04,12280.19,27213.13,247910.08,49855.68,64315.81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2006,29724.44,9731.23,48522.68,28418.46,12947.86,29893.35,287353.27,51082.94,60901.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2007,31535.77,9335.47,49904.61,28248.36,14152.94,32349.9,260381.27,57850.54,73438.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2008,32286.42,9574.36,37349.9,29692.73,14532.68,30787.77,316736.89,51192.39,75335.16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2009,33105.76,9467.72,43767.8,32456.94,15488.44,29984.76,78301.34,50453.01,82076.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,34011.54,10495.29,49313.51,32384.68,16546.74,36315.88,230135.68,61138.2,72693.39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2011,34040.99,10051.3,46355.03,31753.51,16735.62,35492.69,170495.32,63077.42,72131.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2012,34349.87,10177.76,49950.5,32253.68,17218.47,35168.31,140332.24,56021.19,75942.68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2013,35847.5,11755.53,47731.55,34613.65,18117.84,37025.13,116320.48,60331.43,81659.85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2014,35588.57,12484.45,45397.21,36372.69,18432.31,36012.65,108098.33,61770.17,76219.54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,36167.52,13376.65,43597.13,36686.1,18696.02,38815.71,342835.37,74275.32,82007.14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2016,36593.31,14040.74,46712.56,37805.19,19371.47,39246.12,265568.78,77277.06,79977.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2017,37046.6,15543.09,52067.92,37396.61,19402.74,39919,535202.08,73197.63,80114.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2018,37595.21,15859.59,51192.84,37621.93,19860.51,43766.62,328948.99,61416.92,76891.05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2019,38593.35,17779.13,50472.67,37379.5,19743.03,43501.11,273659.89,64655.42,74202.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Apparent labour productivity: total and by ind...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Data Sources: INE - Annual National Accounts (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Source: PORDATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Last updated: 2021-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,The figures presented by the responsible entit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Symbology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,┴,Series break,Pro,Provisional value,Pre,Preliminary value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,...,Confidential,x,Not available,e,Less than half the unit used,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,//,Not applicable,f,Forecast,§,Extremely unreliable value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,-,Absent value,Rv,Revised value,(R),Data rectified by the relevant body,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,N,Negligible value,s,Estimated value,u,Unreliable or uncertain data,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Data obtained in https:www.pordata.pt in 02-06...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,,,,,,,,,,,...,,,,,,,,,,

In [42]:
#Liste the name of columns
ef_productivity.columns

Index(['Years', 'Total', 'Agriculture, forestry and fishing',
       'Mining and quarrying',
       'Manufacture of food products, beverages and tobacco products',
       'Manufacture of textiles, wearing apparel and leather products',
       'Manufacture of wood and paper products, and printing',
       'Manufacture of coke and refined petroleum products',
       'Manufacture of chemicals and chemical products',
       'Manufacture of basic pharmaceutical products and pharmaceutical preparations',
       ...
       'Unnamed: 246', 'Unnamed: 247', 'Unnamed: 248', 'Unnamed: 249',
       'Unnamed: 250', 'Unnamed: 251', 'Unnamed: 252', 'Unnamed: 253',
       'Unnamed: 254', 'Unnamed: 255'],
      dtype='object', length=256)

In [43]:
#Delete all rows with data not relevant
ef_productivity = ef_productivity.drop(labels=range(25, 48), axis=0)

In [44]:
#Delete all columns with NAN values
ef_productivity = ef_productivity.dropna(thresh=10, axis=1)

In [45]:
#Change the types of data have  to be used in visulizations and database
ef_productivity = ef_productivity.astype(float)
ef_productivity['Years'] = ef_productivity['Years'].astype(int)

In [46]:
#Verify that the types of data have changed to be used in visulizations and database
ef_productivity.dtypes

Years                                                                                                                                                                         int64
Total                                                                                                                                                                       float64
Agriculture, forestry and fishing                                                                                                                                           float64
Mining and quarrying                                                                                                                                                        float64
Manufacture of food products, beverages and tobacco products                                                                                                                float64
Manufacture of textiles, wearing apparel and leather products                                                                                                               float64
Manufacture of wood and paper products, and printing                                                                                                                        float64
Manufacture of coke and refined petroleum products                                                                                                                          float64
Manufacture of chemicals and chemical products                                                                                                                              float64
Manufacture of basic pharmaceutical products and pharmaceutical preparations                                                                                                float64
Manufacture of rubber and plastic products, and other non-metallic mineral products                                                                                         float64
Manufacture of basic metals and fabricated metal products, except machinery and equipment                                                                                   float64
Manufacture of computer, electronic and optical products                                                                                                                    float64
Manufacture of electrical equipment                                                                                                                                         float64
Manufacture of machinery and equipment n.e.c.                                                                                                                               float64
Manufacture of transport equipment                                                                                                                                          float64
Manufacture of furniture, other manufacturing, repair and installation of machinery and equipment                                                                           float64
Electricity, gas, steam and air-conditioning supply                                                                                                                         float64
Water supply, sewerage, waste management and remediation activities                                                                                                         float64
Construction                                                                                                                                                                float64
Wholesale and retail trade, repair of motor vehicles and motorcycles                                                                                                        float64
Transportation and storage                                                                                                                                                  float64
Accommodation and food service activities                                                                                                                                   float64
Publishing, audiovisual and broadcasting activities                                                                                                                         float64
Telecommunications                                                                                                                                                          float64
Computer programming, consultancy and related activities, information service activities                                                                                    float64
Financial and insurance activities                                                                                                                                          float64
Real estate activities                                                                                                                                                      float64
Legal and accounting activities, activities of head offices, management consultancy activities, architectural and engineering activities, technical testing and analysis    float64
Scientific research and development                                                                                                                                         float64
Advertising and market research, other professional, scientific and technical activities, veterinary activities                                                             float64
Administrative and support service activities                                                                                                                               float64
Public administration and defence, compulsory social security                                                                                                               float64
Education                                                                                                                                                                   float64
Human health activities                                                                                                                                                     float64
Social work activities                                                                                                                                                      float64
Arts, entertainment and recreation                                                                                                                                          float64
Other service activities                                                                                                                                                    float64
Activities of households as employers of domestic personnel and undifferentiated goods and services production of households for own use                                    float64
dtype: object

In [47]:
#Rename the columns by code "Col_" plus position
ef_productivity.columns = ['Col_' + str(i) if 3 <= i <= 39 else x for i, x in enumerate(ef_productivity.columns, 1)]

In [48]:
#Delete columns Col_39
ef_productivity = ef_productivity.drop(labels=['Col_39'], axis=1)

In [49]:
#Transpose
ef_productivity = ef_productivity.T

#Rename the columns name with the values of the row index 0 
ef_productivity.rename(columns=ef_productivity.iloc[0], inplace = True)

ef_productivity = ef_productivity.drop(labels=['Years'], axis=0)
ef_productivity = ef_productivity.drop(labels=['Total'], axis=0)


cols=range(1995, 2020)
ef_productivity.columns=cols

In [50]:
#Export to CSV file
ef_productivity.to_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Efficiency_and _Return/labour_productivity.csv', index=True)
ef_productivity

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Col_3,9161.38,9159.26,8239.76,8605.59,8902.29,8809.10,8842.20,8967.58,9018.98,9753.43,...,10495.29,10051.30,10177.76,11755.53,12484.45,13376.65,14040.74,15543.09,15859.59,17779.13
Col_4,34275.96,30249.94,32103.77,33141.17,32997.47,33664.85,34895.48,31143.81,30072.39,35695.46,...,49313.51,46355.03,49950.50,47731.55,45397.21,43597.13,46712.56,52067.92,51192.84,50472.67
Col_5,13823.52,15590.86,16629.32,18311.62,20902.23,20071.00,22226.07,24584.47,25985.42,27291.87,...,32384.68,31753.51,32253.68,34613.65,36372.69,36686.10,37805.19,37396.61,37621.93,37379.50
Col_6,9446.11,10226.27,10434.46,10345.16,10726.39,10623.54,10966.11,11785.40,12275.85,12372.61,...,16546.74,16735.62,17218.47,18117.84,18432.31,18696.02,19371.47,19402.74,19860.51,19743.03
Col_7,18950.96,18178.73,19732.40,20836.64,21764.65,25647.79,25203.06,25297.29,24996.96,25206.05,...,36315.88,35492.69,35168.31,37025.13,36012.65,38815.71,39246.12,39919.00,43766.62,43501.11
Col_8,27285.81,41255.79,58558.36,96756.29,61307.90,83195.16,86683.10,72880.59,83605.85,154551.52,...,230135.68,170495.32,140332.24,116320.48,108098.33,342835.37,265568.78,535202.08,328948.99,273659.89
Col_9,39621.88,41379.97,44715.01,41166.52,39271.06,41428.41,42311.71,42265.63,43359.51,48517.71,...,61138.20,63077.42,56021.19,60331.43,61770.17,74275.32,77277.06,73197.63,61416.92,64655.42
Col_10,39943.85,41651.83,44983.36,42844.63,41121.74,44979.57,52361.91,55726.95,57666.51,62245.61,...,72693.39,72131.29,75942.68,81659.85,76219.54,82007.14,79977.29,80114.48,76891.05,74202.84
Col_11,20043.15,20867.66,23002.01,24736.90,25309.62,25289.60,25790.33,26744.13,26249.63,27378.70,...,35622.89,35331.39,35453.36,37269.34,37374.63,38762.70,39704.75,40580.55,40953.61,43244.63
Col_12,15072.67,14666.63,15612.85,16364.97,17012.52,18240.00,18469.83,19441.73,19316.16,21147.74,...,25615.86,24924.29,25334.73,26541.53,27772.65,26826.22,29156.64,30316.76,31010.93,31578.15
Col_13,40217.01,42848.10,45551.78,48670.81,49374.48,51558.94,51120.16,47074.24,48229.42,51242.48,...,59797.61,45881.74,39914.84,42761.02,41190.52,41361.89,43668.39,43806.21,42954.35,43178.42
Col_14,19302.89,20239.00,21386.45,22730.51,23795.40,24117.17,26414.79,29151.94,29575.55,31581.40,...,40158.27,37317.73,35636.93,33933.23,33602.62,33632.92,33245.82,34677.93,33589.29,34072.18
Col_15,14900.29,16524.47,17902.25,18977.95,21519.84,23303.64,23644.54,25297.26,25086.68,25283.53,...,33394.09,31288.56,35314.60,36513.14,39743.25,38215.22,37744.07,37653.76,37245.25,37279.08
Col_16,12946.96,23570.91,25620.27,26313.28,26300.55,26481.51,28196.43,28856.75,27265.08,28836.25,...,34775.21,36307.27,34594.07,36420.28,37297.26,37043.60,36259.98,36427.94,37700.80,39128.12
Col_17,11515.72,11968.25,12669.49,13258.44,14227.75,14857.20,15885.65,16561.20,16759.84,17432.43,...,22447.40,22152.53,22667.12,23391.34,23905.27,24098.48,23725.16,24216.60,25183.93,26867.17
Col_18,117115.94,128386.88,126546.01,145280.74,147108.77,148111.86,168058.60,194867.78,224668.09,251088.72,...,385649.47,372413.19,399795.24,417411.87,481833.46,538454.71,546978.28,478324.65,516737.71,496269.08
Col_19,13453.25,14770.97,15514.72,17209.44,19844.66,21723.27,22082.66,24728.01,27178.74,29969.35,...,43152.51,43721.22,44312.84,44059.23,44252.38,42962.61,42036.83,39961.46,40069.57,41509.46
Col_20,12184.18,12731.64,14009.07,13956.47,14480.61,14717.23,16154.93,15849.13,16138.78,17379.43,...,20644.38,21018.81,22522.52,23590.58,23112.60,23106.65,23367.40,23426.22,24266.05,24871.77
Col_21,18870.36,19686.17,21414.69,21562.13,21914.63,23539.95,23302.81,24354.86,24125.32,24382.20,...,28833.02,30719.13,32612.28,34764.44,33403.42,33634.12,33598.02,32844.31,32362.29,32806.03
Col_22,22455.65,24304.19,26090.32,27725.13,29670.76,31028.18,31315.24,32311.95,32795.54,33562.10,...,43713.61,42943.60,43915.98,46584.11,45163.13,47117.64,46913.04,48903.63,48835.76,49485.91
Col_23,16786.24,16124.09,17265.88,18143.44,19768.21,21806.81,21645.55,23421.42,24005.90,24937.55,...,28078.21,28051.85,29630.86,29719.72,29738.06,29806.14,30650.54,31808.68,31642.71,32261.67
Col_24,22646.67,21867.37,24121.70,24927.62,28527.69,33474.93,34691.38,35651.77,37842.67,41434.52,...,50138.79,50237.98,47592.52,50975.11,50061.78,48292.21,49678.85,53753.50,54482.86,57512.70
Col_25,119098.74,129083.32,137696.14,141391.14,149778.30,172868.60,199759.28,220983.21,237775.33,245448.27,...,217697.92,223976.04,199256.36,178897.08,170245.99,155852.47,164405.78,161818.10,156791.90,173830.56
Col_26,28805.23,28715.77,30182.41,33104.18,36442.10,34239.04,39414.63,40067.16,41123.33,41269.58,...,43185.57,41792.33,41147.56,40814.20,40553.51,39374.35,40521.53,41692.40,41951.06,45183.03
Col_27,49383.34,47049.84,56146.06,62516.84,66779.23,69480.17,85325.89,89179.09,97467.12,107769.90,...,111978.31,114907.66,101632.48,93006.86,94128.02,98924.12,101071.59,105190.78,106289.66,110204.38
Col_28,272408.29,274599.08,268297.24,277581.00,289777.63,276569.52,296793.49,331690.06,355223.83,389805.43,...,538504.46,495654.01,585443.37,623134.55,596097.48,570492.12,526494.46,471769.73,452365.48,436099.26
Col_29,20035.68,21227.86,21160.64,22632.18,24499.75,25908.84,25769.17,25379.97,26314.11,26493.42,...,29688.54,29399.25,28791.33,29115.15,29495.49,27748.78,27537.75,29095.05,31344.68,32664.93
Col_30,8097.20,9172.19,10816.99,12588.00,13378.74,14651.69,16961.60,19112.30,20483.02,21856.42,...,55966.30,52976.35,58294.24,65394.94,72191.14,63522.57,63313.70,55497.07,58700.72,60978.99
Col_31,21598.21,20381.38,21154.73,23780.44,26110.28,27614.54,27048.83,27899.45,27837.86,29587.38,...,32426.60,30433.00,28487.14,28871.46,27484.83,27761.61,28123.54,28884.82,31075.83,33523.13
Col_32,11738.17,12124.61,12244.51,12950.75,14101.30,14388.38,14458.97,15175.05,15501.17,15777.17,...,18621.64,18211.98,17977.23,18206.99,17774.82,17808.23,18412.50,18746.08,19477.01,20334.69
Col_33,22053.32,23383.72,25279.28,27200.27,28367.73,31025.20,31556.47,31528.07,33647.76,34078.87,...,41154.39,40789.93,36921.81,41334.57,39166.54,39993.93,40708.13,41445.10,42633.15,43441.51
Col_34,19218.57,19622.55,20695.22,21679.60,22715.22,24888.28,26539.78,28408.36,29904.52,31243.36,...,34696.19,32378.61,29334.78,31096.68,31786.79,31789.01,31644.01,32425.89,32934.26,33662.96
Col_35,17200.75,18353.71,19052.19,20314.15,21506.39,23074.24,26345.95,27518.60,29168.78,31293.75,...,34785.57,32929.34,31710.50,32058.31,32078.89,32273.31,32472.86,33062.50,34272.16,35697.77
Col_36,10392.42,10269.30,10711.30,10858.10,10920.68,11828.15,13653.45,13627.21,13562.98,14362.82,...,16443.28,16762.92,16761.39,16781.71,16271.78,16775.42,17508.39,18833.64,19288.95,19509.61
Col_37,17176.91,19070.63,19439.74,16923.08,19383.45,22298.65,23334.81,25285.22,26152.39,27139.79,...,28783.38,30142.69,27204.13,26528.61,26512.09,28470.20,28283.83,29956.18,31503.69,32427.68
Col_38,8204.01,9064.84,8882.13,8870.18,9554.09,11660.54,11514.27,12636.37,12741.39,13120.74,...,18243.86,17900.96,19748.07,19832.12,19448.11,19809.62,19910.60,20249.42,20914.36,21199.05

### 2.2 For the file (Investment rate total and by industry.xlsx)

In [51]:
#Import data using pandas
ef_invest=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Efficiency_and _Return/Investment rate total and by industry.xlsx")
ef_invest

,Years,Total,"Agriculture, forestry and fishing",Mining and quarrying,"Manufacture of food products, beverages and tobacco products","Manufacture of textiles, wearing apparel and leather products","Manufacture of wood and paper products, and printing",Manufacture of coke and refined petroleum products,Manufacture of chemicals and chemical products,Manufacture of basic pharmaceutical products and pharmaceutical preparations,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,1995,26.4,15.6,14,12.8,7.7,8.1,78.9,9.7,10.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996,27.1,16.9,25.2,16,8,12.3,64.5,11.4,11.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997,29.5,19.5,30.6,13.8,9.1,14.1,109.4,21.8,17.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998,31.3,22.7,29.2,15.2,12,12.7,14.8,19.8,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1999,31.7,25.1,32.1,15.1,10.6,19.3,200,24.3,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,32,23.8,36.8,19.1,12.7,19.5,177.5,22.7,37.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2001,31.2,24.9,35.8,18.2,12.1,18,171.4,17.7,27.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2002,29.6,28.7,20.8,19.7,8.6,17.8,103.7,20.8,41.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2003,27.2,27,16.6,19.4,7.4,18.6,74.8,17.5,38.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2004,26.8,28.3,15.5,18.9,6.9,18.1,53.5,16.5,35.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2005,26.7,26.9,15.8,18.1,6.8,16.6,24.2,17,41.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2006,26.1,26,17.5,18.7,3.4,15.4,16.1,22.1,44.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2007,26,28.6,21.8,23.4,5.1,17.3,22.7,30.5,33.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2008,26.2,30.2,23.2,26.7,6.3,32.6,50.2,43.5,32.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2009,23.9,25.8,19.1,20.5,4.9,38.1,222.6,45.5,31.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,23.4,27.2,24.3,19.7,6.3,15.8,182.8,28.6,33.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2011,21,29.2,24.8,21.2,6.7,12.9,208.8,46,35.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2012,18.1,27.3,21.3,20.8,7.6,13.6,74.2,48.4,34.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2013,16.8,25.6,26.2,19,9.3,15.1,30,38.3,29.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2014,17.2,27.2,31.7,19.7,10.7,19.2,55,27.5,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,17.8,29.5,26.4,19.1,9.7,20.8,11.5,18.2,38.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2016,17.8,27.2,22.6,16.4,12,24.1,21.8,18.7,44.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2017,19.4,28.1,32.9,21.3,12.8,34.3,8.7,24,40.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2018,20.3,27.6,50.2,21.8,12,29.5,27.2,39.3,49.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2019,20.9,26.3,59.6,22.4,11.1,23.3,40.6,32.8,51.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Investment rate: total and by industry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Data Sources: INE - Annual National Accounts (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Source: PORDATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Last updated: 2021-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,The figures presented by the responsible entit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Symbology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,┴,Series break,Pro,Provisional value,Pre,Preliminary value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,...,Confidential,x,Not available,e,Less than half the unit used,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,//,Not applicable,f,Forecast,§,Extremely unreliable value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,-,Absent value,Rv,Revised value,(R),Data rectified by the relevant body,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,N,Negligible value,s,Estimated value,u,Unreliable or uncertain data,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Data obtained in https:www.pordata.pt in 02-06...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,,,,,,,,,,,...,,,,,,,,,,

In [52]:
#Liste the name of columns
ef_invest.columns

#Delete all rows with data not relevant
ef_invest = ef_invest.drop(labels=range(25, 48), axis=0)

#Delete all columns with NAN values
ef_invest = ef_invest.dropna(thresh=10, axis=1)

#Change the types of data have  to be used in visulizations and database
ef_invest = ef_invest.astype(float)
ef_invest['Years'] = ef_invest['Years'].astype(int)

In [53]:
#Verify that the types of data have changed to be used in visulizations and database
ef_invest.dtypes

Years                                                                                                                                                                         int64
Total                                                                                                                                                                       float64
Agriculture, forestry and fishing                                                                                                                                           float64
Mining and quarrying                                                                                                                                                        float64
Manufacture of food products, beverages and tobacco products                                                                                                                float64
Manufacture of textiles, wearing apparel and leather products                                                                                                               float64
Manufacture of wood and paper products, and printing                                                                                                                        float64
Manufacture of coke and refined petroleum products                                                                                                                          float64
Manufacture of chemicals and chemical products                                                                                                                              float64
Manufacture of basic pharmaceutical products and pharmaceutical preparations                                                                                                float64
Manufacture of rubber and plastic products, and other non-metallic mineral products                                                                                         float64
Manufacture of basic metals and fabricated metal products, except machinery and equipment                                                                                   float64
Manufacture of computer, electronic and optical products                                                                                                                    float64
Manufacture of electrical equipment                                                                                                                                         float64
Manufacture of machinery and equipment n.e.c.                                                                                                                               float64
Manufacture of transport equipment                                                                                                                                          float64
Manufacture of furniture, other manufacturing, repair and installation of machinery and equipment                                                                           float64
Electricity, gas, steam and air-conditioning supply                                                                                                                         float64
Water supply, sewerage, waste management and remediation activities                                                                                                         float64
Construction                                                                                                                                                                float64
Wholesale and retail trade, repair of motor vehicles and motorcycles                                                                                                        float64
Transportation and storage                                                                                                                                                  float64
Accommodation and food service activities                                                                                                                                   float64
Publishing, audiovisual and broadcasting activities                                                                                                                         float64
Telecommunications                                                                                                                                                          float64
Computer programming, consultancy and related activities, information service activities                                                                                    float64
Financial and insurance activities                                                                                                                                          float64
Real estate activities                                                                                                                                                      float64
Legal and accounting activities, activities of head offices, management consultancy activities, architectural and engineering activities, technical testing and analysis    float64
Scientific research and development                                                                                                                                         float64
Advertising and market research, other professional, scientific and technical activities, veterinary activities                                                             float64
Administrative and support service activities                                                                                                                               float64
Public administration and defence, compulsory social security                                                                                                               float64
Education                                                                                                                                                                   float64
Human health activities                                                                                                                                                     float64
Social work activities                                                                                                                                                      float64
Arts, entertainment and recreation                                                                                                                                          float64
Other service activities                                                                                                                                                    float64
dtype: object

In [54]:
#Rename the columns by code "Col_" plus position
ef_invest.columns = ['Col_' + str(i) if 3 <= i <= 39 else x for i, x in enumerate(ef_invest.columns, 1)]

In [55]:
#Transpose
ef_invest = ef_invest.T

#Rename the columns name with the values of the row index 0 
ef_invest.rename(columns=ef_invest.iloc[0], inplace = True)

ef_invest = ef_invest.drop(labels=['Years'], axis=0)
ef_invest = ef_invest.drop(labels=['Total'], axis=0)

cols=range(1995, 2020)
ef_invest.columns=cols

In [56]:
#Export to CSV file
ef_invest.to_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Efficiency_and _Return/investment.csv', index=True)
ef_invest

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Col_3,15.6,16.9,19.5,22.7,25.1,23.8,24.9,28.7,27.0,28.3,...,27.2,29.2,27.3,25.6,27.2,29.5,27.2,28.1,27.6,26.3
Col_4,14.0,25.2,30.6,29.2,32.1,36.8,35.8,20.8,16.6,15.5,...,24.3,24.8,21.3,26.2,31.7,26.4,22.6,32.9,50.2,59.6
Col_5,12.8,16.0,13.8,15.2,15.1,19.1,18.2,19.7,19.4,18.9,...,19.7,21.2,20.8,19.0,19.7,19.1,16.4,21.3,21.8,22.4
Col_6,7.7,8.0,9.1,12.0,10.6,12.7,12.1,8.6,7.4,6.9,...,6.3,6.7,7.6,9.3,10.7,9.7,12.0,12.8,12.0,11.1
Col_7,8.1,12.3,14.1,12.7,19.3,19.5,18.0,17.8,18.6,18.1,...,15.8,12.9,13.6,15.1,19.2,20.8,24.1,34.3,29.5,23.3
Col_8,78.9,64.5,109.4,14.8,200.0,177.5,171.4,103.7,74.8,53.5,...,182.8,208.8,74.2,30.0,55.0,11.5,21.8,8.7,27.2,40.6
Col_9,9.7,11.4,21.8,19.8,24.3,22.7,17.7,20.8,17.5,16.5,...,28.6,46.0,48.4,38.3,27.5,18.2,18.7,24.0,39.3,32.8
Col_10,10.2,11.8,17.8,17.0,20.0,37.5,27.7,41.3,38.3,35.7,...,33.2,35.8,34.1,29.3,33.0,38.1,44.9,40.9,49.8,51.2
Col_11,17.2,19.3,18.3,18.8,23.2,27.9,25.3,26.8,20.4,23.5,...,19.3,19.9,21.6,22.8,26.1,23.7,25.8,25.1,26.9,25.4
Col_12,11.1,12.6,14.2,17.1,17.4,22.0,20.4,17.6,16.9,16.8,...,15.5,15.6,15.3,17.6,19.5,22.0,24.7,25.5,24.3,22.1
Col_13,27.0,24.2,24.1,139.5,29.6,30.1,30.5,32.5,33.2,40.6,...,23.3,33.5,36.7,28.2,37.8,33.8,49.6,46.6,51.9,57.0
Col_14,14.0,13.8,14.2,85.1,17.2,17.3,18.9,16.5,15.6,15.5,...,24.4,29.6,26.0,22.8,24.2,23.0,36.0,30.1,43.0,34.5
Col_15,41.3,46.3,41.0,51.1,44.7,45.4,42.2,36.6,37.7,36.4,...,18.8,19.8,20.8,19.2,18.5,19.1,23.4,26.6,30.6,31.6
Col_16,37.7,29.6,21.1,39.2,25.4,20.7,21.7,20.8,20.3,24.5,...,36.8,29.8,30.7,25.1,25.6,30.5,43.9,52.2,40.5,40.3
Col_17,12.3,15.3,13.0,28.1,18.3,22.6,18.7,17.4,15.7,12.4,...,15.7,14.7,14.8,12.3,17.8,15.9,17.1,18.4,19.2,18.7
Col_18,18.4,10.0,28.7,9.7,34.9,35.5,27.2,30.6,31.7,31.4,...,56.8,58.0,49.7,53.2,39.5,31.9,27.6,30.2,27.7,30.7
Col_19,77.6,61.3,77.7,70.9,88.4,92.9,85.4,57.0,60.7,61.6,...,80.4,60.8,48.6,39.9,41.7,34.2,27.4,34.8,36.2,45.6
Col_20,22.5,22.6,24.0,23.3,23.2,23.6,20.1,13.7,13.8,16.2,...,12.1,12.7,10.5,9.8,11.0,10.0,7.8,9.7,11.5,12.4
Col_21,9.5,10.5,10.4,13.0,13.4,14.1,13.1,12.7,12.5,11.3,...,10.4,8.2,7.0,7.0,8.6,8.8,9.5,9.9,10.5,12.7
Col_22,36.4,36.1,45.5,42.9,48.2,49.7,57.6,58.6,64.6,60.7,...,18.1,31.4,20.9,19.9,18.8,24.4,21.0,23.7,22.0,23.2
Col_23,13.8,13.0,13.5,12.4,12.3,12.8,12.0,12.9,10.6,10.3,...,14.8,12.0,10.3,8.4,9.1,11.3,11.7,13.2,14.3,16.2
Col_24,42.9,43.3,48.0,56.5,55.0,50.6,60.3,64.4,59.1,60.3,...,47.0,46.6,46.9,44.2,47.8,50.0,46.9,49.4,48.6,45.7
Col_25,32.0,32.8,34.9,36.1,46.7,44.7,50.1,44.8,33.1,37.5,...,50.8,38.5,38.0,42.4,47.5,48.4,38.8,48.0,46.3,37.9
Col_26,25.8,27.2,31.0,30.3,29.8,31.2,35.0,33.9,39.4,39.4,...,33.9,31.8,32.7,33.5,30.7,31.0,28.4,31.2,30.0,31.7
Col_27,19.3,21.4,19.6,18.7,13.5,12.2,12.4,15.6,10.5,12.5,...,8.0,8.4,5.8,9.9,1.5,-1.7,4.6,2.6,2.4,3.5
Col_28,109.7,106.7,114.1,119.1,120.9,123.6,123.2,112.8,91.7,90.2,...,42.9,37.1,30.9,24.4,27.8,29.7,30.3,31.4,35.7,37.4
Col_29,9.0,10.0,11.6,12.0,12.5,11.5,10.8,14.3,15.5,16.4,...,13.5,13.9,11.0,11.6,12.2,11.1,13.6,14.3,14.7,15.3
Col_30,251.8,243.3,220.4,201.6,207.5,189.9,182.0,212.5,222.3,174.2,...,110.5,101.5,91.4,98.7,93.3,94.5,82.5,88.8,83.9,75.1
Col_31,14.3,17.0,19.4,18.7,18.0,22.2,23.7,24.3,21.0,19.0,...,13.2,13.8,12.3,10.8,11.7,11.8,12.4,12.3,16.5,20.1
Col_32,19.4,20.9,23.3,24.3,24.9,30.0,28.5,24.3,26.1,21.9,...,13.0,12.9,9.5,9.3,13.4,15.8,20.5,21.3,20.9,21.2
Col_33,43.7,51.3,55.4,47.7,45.4,39.2,42.0,38.0,34.1,34.8,...,46.7,28.3,19.8,15.8,14.2,17.1,11.4,15.4,15.9,15.6
Col_34,11.4,9.2,10.1,10.4,13.5,10.9,12.2,10.2,8.9,8.7,...,11.9,12.7,13.3,11.3,11.5,12.3,12.0,12.8,12.6,11.8
Col_35,13.8,13.0,16.4,18.6,18.4,21.4,17.7,14.9,15.7,10.7,...,14.8,14.0,13.2,11.8,12.3,14.2,13.6,14.0,14.3,14.6
Col_36,36.7,40.6,52.6,53.5,55.0,48.0,44.8,42.7,33.1,28.0,...,25.8,26.3,20.6,20.2,8.9,9.1,8.5,9.5,10.3,10.5
Col_37,30.1,27.8,31.3,35.0,34.8,35.5,36.0,48.9,46.7,38.6,...,33.6,29.6,28.9,27.2,32.4,31.6,34.0,32.5,36.9,37.1
Col_38,30.8,29.3,33.2,39.8,34.8,31.2,18.2,15.4,14.3,14.7,...,8.6,9.1,12.2,10.6,13.5,13.8,13.2,13.7,13.6,13.1

### 2.3. For the file (Degree of production processing total and by industry.xlsx)

In [57]:
#Import data using pandas
ef_degree_production=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Efficiency_and _Return/Degree of production processing total and by industry.xlsx")
ef_degree_production

,Years,Total,"Agriculture, forestry and fishing",Mining and quarrying,"Manufacture of food products, beverages and tobacco products","Manufacture of textiles, wearing apparel and leather products","Manufacture of wood and paper products, and printing",Manufacture of coke and refined petroleum products,Manufacture of chemicals and chemical products,Manufacture of basic pharmaceutical products and pharmaceutical preparations,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,1995,0.46,0.62,0.61,0.16,0.33,0.33,0.05,0.3,0.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996,0.45,0.6,0.57,0.17,0.34,0.34,0.07,0.3,0.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997,0.45,0.58,0.58,0.18,0.33,0.35,0.08,0.29,0.41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998,0.46,0.58,0.59,0.2,0.33,0.34,0.13,0.26,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1999,0.46,0.56,0.58,0.22,0.35,0.34,0.07,0.26,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,0.46,0.56,0.56,0.21,0.33,0.34,0.06,0.24,0.39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2001,0.46,0.55,0.54,0.22,0.33,0.34,0.06,0.25,0.39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2002,0.47,0.54,0.52,0.23,0.35,0.34,0.05,0.25,0.41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2003,0.48,0.54,0.51,0.24,0.35,0.32,0.06,0.24,0.41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2004,0.47,0.53,0.52,0.24,0.35,0.31,0.08,0.23,0.41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2005,0.47,0.51,0.51,0.24,0.35,0.33,0.1,0.22,0.41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2006,0.47,0.51,0.55,0.24,0.35,0.34,0.09,0.2,0.37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2007,0.47,0.47,0.52,0.22,0.36,0.33,0.08,0.21,0.39,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2008,0.46,0.45,0.44,0.22,0.38,0.31,0.08,0.18,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2009,0.49,0.47,0.52,0.24,0.41,0.32,0.03,0.22,0.42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,0.48,0.46,0.52,0.24,0.39,0.33,0.06,0.19,0.38,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2011,0.47,0.42,0.49,0.22,0.38,0.3,0.04,0.17,0.37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2012,0.48,0.41,0.5,0.22,0.38,0.28,0.03,0.14,0.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2013,0.49,0.44,0.49,0.22,0.38,0.28,0.02,0.15,0.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2014,0.49,0.44,0.48,0.23,0.37,0.27,0.02,0.16,0.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,0.49,0.45,0.45,0.24,0.38,0.28,0.08,0.2,0.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2016,0.5,0.46,0.48,0.25,0.38,0.28,0.07,0.23,0.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2017,0.49,0.46,0.49,0.24,0.37,0.27,0.12,0.2,0.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2018,0.48,0.45,0.44,0.24,0.38,0.28,0.07,0.17,0.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2019,0.49,0.46,0.44,0.24,0.38,0.28,0.06,0.17,0.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2020,0.49,0.45,0.43,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Degree of production processing: total and by ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Data Sources: INE - Annual National Accounts (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Source: PORDATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Last updated: 2022-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,The figures presented by the responsible entit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Symbology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,┴,Series break,Pro,Provisional value,Pre,Preliminary value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,...,Confidential,x,Not available,e,Less than half the unit used,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,//,Not applicable,f,Forecast,§,Extremely unreliable value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,-,Absent value,Rv,Revised value,(R),Data rectified by the relevant body,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,N,Negligible value,s,Estimated value,u,Unreliable or uncertain data,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Data obtained in https:www.pordata.pt in 02-06...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,,,,,,,,,,,...,,,,,,,,,,

In [58]:
#Liste the name of columns
ef_degree_production.columns

#Delete all rows with data not relevant
ef_degree_production = ef_degree_production.drop(labels=range(25, 49), axis=0)

#Delete all columns with NAN values
ef_degree_production = ef_degree_production.dropna(thresh=10, axis=1)

#Change the types of data have  to be used in visulizations and database
ef_degree_production = ef_degree_production.astype(float)
ef_degree_production['Years'] = ef_degree_production['Years'].astype(int)

In [59]:
#Verify that the types of data have changed to be used in visulizations and database
ef_degree_production.dtypes

Years                                                                                                                                                                         int64
Total                                                                                                                                                                       float64
Agriculture, forestry and fishing                                                                                                                                           float64
Mining and quarrying                                                                                                                                                        float64
Manufacture of food products, beverages and tobacco products                                                                                                                float64
Manufacture of textiles, wearing apparel and leather products                                                                                                               float64
Manufacture of wood and paper products, and printing                                                                                                                        float64
Manufacture of coke and refined petroleum products                                                                                                                          float64
Manufacture of chemicals and chemical products                                                                                                                              float64
Manufacture of basic pharmaceutical products and pharmaceutical preparations                                                                                                float64
Manufacture of rubber and plastic products, and other non-metallic mineral products                                                                                         float64
Manufacture of basic metals and fabricated metal products, except machinery and equipment                                                                                   float64
Manufacture of computer, electronic and optical products                                                                                                                    float64
Manufacture of electrical equipment                                                                                                                                         float64
Manufacture of machinery and equipment n.e.c.                                                                                                                               float64
Manufacture of transport equipment                                                                                                                                          float64
Manufacture of furniture, other manufacturing, repair and installation of machinery and equipment                                                                           float64
Electricity, gas, steam and air-conditioning supply                                                                                                                         float64
Water supply, sewerage, waste management and remediation activities                                                                                                         float64
Construction                                                                                                                                                                float64
Wholesale and retail trade, repair of motor vehicles and motorcycles                                                                                                        float64
Transportation and storage                                                                                                                                                  float64
Accommodation and food service activities                                                                                                                                   float64
Publishing, audiovisual and broadcasting activities                                                                                                                         float64
Telecommunications                                                                                                                                                          float64
Computer programming, consultancy and related activities, information service activities                                                                                    float64
Financial and insurance activities                                                                                                                                          float64
Real estate activities                                                                                                                                                      float64
Legal and accounting activities, activities of head offices, management consultancy activities, architectural and engineering activities, technical testing and analysis    float64
Scientific research and development                                                                                                                                         float64
Advertising and market research, other professional, scientific and technical activities, veterinary activities                                                             float64
Administrative and support service activities                                                                                                                               float64
Public administration and defence, compulsory social security                                                                                                               float64
Education                                                                                                                                                                   float64
Human health activities                                                                                                                                                     float64
Social work activities                                                                                                                                                      float64
Arts, entertainment and recreation                                                                                                                                          float64
Other service activities                                                                                                                                                    float64
Activities of households as employers of domestic personnel and undifferentiated goods and services production of households for own use                                    float64
dtype: object

In [60]:
#Rename the columns by code "Col_" plus position
ef_degree_production.columns = ['Col_' + str(i) if 3 <= i <= 39 else x for i, x in enumerate(ef_degree_production.columns, 1)]

In [61]:
#Delete columns Col_39
ef_degree_production = ef_degree_production.drop(labels=['Col_39'], axis=1)

In [62]:
#Transpose
ef_degree_production = ef_degree_production.T

#Rename the columns name with the values of the row index 0 
ef_degree_production.rename(columns=ef_degree_production.iloc[0], inplace = True)

ef_degree_production = ef_degree_production.drop(labels=['Years'], axis=0)
ef_degree_production = ef_degree_production.drop(labels=['Total'], axis=0)


cols=range(1995, 2020)
ef_degree_production.columns=cols

In [63]:
#Export to CSV file
ef_degree_production.to_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Efficiency_and _Return/degree_production.csv', index=True)
ef_degree_production

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Col_3,0.62,0.60,0.58,0.58,0.56,0.56,0.55,0.54,0.54,0.53,...,0.46,0.42,0.41,0.44,0.44,0.45,0.46,0.46,0.45,0.46
Col_4,0.61,0.57,0.58,0.59,0.58,0.56,0.54,0.52,0.51,0.52,...,0.52,0.49,0.50,0.49,0.48,0.45,0.48,0.49,0.44,0.44
Col_5,0.16,0.17,0.18,0.20,0.22,0.21,0.22,0.23,0.24,0.24,...,0.24,0.22,0.22,0.22,0.23,0.24,0.25,0.24,0.24,0.24
Col_6,0.33,0.34,0.33,0.33,0.35,0.33,0.33,0.35,0.35,0.35,...,0.39,0.38,0.38,0.38,0.37,0.38,0.38,0.37,0.38,0.38
Col_7,0.33,0.34,0.35,0.34,0.34,0.34,0.34,0.34,0.32,0.31,...,0.33,0.30,0.28,0.28,0.27,0.28,0.28,0.27,0.28,0.28
Col_8,0.05,0.07,0.08,0.13,0.07,0.06,0.06,0.05,0.06,0.08,...,0.06,0.04,0.03,0.02,0.02,0.08,0.07,0.12,0.07,0.06
Col_9,0.30,0.30,0.29,0.26,0.26,0.24,0.25,0.25,0.24,0.23,...,0.19,0.17,0.14,0.15,0.16,0.20,0.23,0.20,0.17,0.17
Col_10,0.43,0.43,0.41,0.40,0.40,0.39,0.39,0.41,0.41,0.41,...,0.38,0.37,0.40,0.43,0.44,0.43,0.45,0.47,0.44,0.43
Col_11,0.38,0.39,0.39,0.40,0.41,0.38,0.37,0.37,0.36,0.35,...,0.34,0.32,0.32,0.33,0.32,0.33,0.34,0.33,0.33,0.34
Col_12,0.32,0.33,0.32,0.32,0.33,0.31,0.31,0.32,0.30,0.29,...,0.30,0.27,0.27,0.28,0.29,0.28,0.31,0.30,0.30,0.31
Col_13,0.26,0.29,0.30,0.30,0.29,0.27,0.29,0.24,0.23,0.24,...,0.30,0.23,0.23,0.26,0.26,0.25,0.24,0.21,0.21,0.19
Col_14,0.35,0.37,0.38,0.38,0.37,0.36,0.36,0.37,0.36,0.35,...,0.26,0.24,0.24,0.24,0.24,0.23,0.24,0.24,0.24,0.26
Col_15,0.27,0.28,0.28,0.27,0.29,0.28,0.27,0.29,0.28,0.27,...,0.30,0.28,0.32,0.32,0.32,0.34,0.33,0.33,0.33,0.34
Col_16,0.13,0.19,0.20,0.20,0.20,0.21,0.22,0.21,0.20,0.21,...,0.20,0.18,0.18,0.19,0.19,0.18,0.18,0.17,0.17,0.16
Col_17,0.39,0.38,0.39,0.38,0.40,0.39,0.41,0.42,0.41,0.41,...,0.39,0.40,0.41,0.41,0.40,0.40,0.40,0.39,0.40,0.41
Col_18,0.38,0.42,0.42,0.42,0.39,0.35,0.33,0.34,0.36,0.35,...,0.26,0.24,0.24,0.24,0.27,0.31,0.31,0.26,0.29,0.28
Col_19,0.38,0.38,0.38,0.38,0.38,0.37,0.36,0.36,0.39,0.40,...,0.42,0.42,0.43,0.44,0.45,0.43,0.43,0.39,0.39,0.40
Col_20,0.29,0.28,0.28,0.28,0.29,0.29,0.29,0.29,0.30,0.29,...,0.30,0.31,0.35,0.37,0.37,0.38,0.39,0.37,0.36,0.35
Col_21,0.55,0.53,0.55,0.54,0.53,0.54,0.54,0.55,0.55,0.54,...,0.56,0.59,0.62,0.64,0.62,0.61,0.61,0.59,0.58,0.58
Col_22,0.48,0.46,0.46,0.45,0.47,0.45,0.44,0.44,0.43,0.42,...,0.41,0.39,0.40,0.41,0.40,0.39,0.40,0.40,0.39,0.39
Col_23,0.44,0.43,0.46,0.48,0.50,0.51,0.50,0.52,0.53,0.54,...,0.55,0.55,0.57,0.57,0.55,0.55,0.56,0.56,0.56,0.55
Col_24,0.25,0.26,0.27,0.27,0.29,0.31,0.31,0.33,0.34,0.35,...,0.37,0.37,0.36,0.39,0.38,0.37,0.38,0.40,0.41,0.42
Col_25,0.50,0.48,0.48,0.47,0.48,0.45,0.42,0.45,0.45,0.45,...,0.41,0.46,0.45,0.43,0.45,0.47,0.46,0.43,0.43,0.45
Col_26,0.41,0.39,0.39,0.40,0.42,0.42,0.43,0.45,0.44,0.44,...,0.50,0.51,0.51,0.52,0.52,0.52,0.54,0.55,0.55,0.56
Col_27,0.74,0.70,0.70,0.67,0.65,0.63,0.65,0.64,0.65,0.65,...,0.61,0.61,0.57,0.54,0.55,0.56,0.57,0.58,0.57,0.59
Col_28,0.77,0.75,0.74,0.74,0.76,0.76,0.72,0.74,0.75,0.76,...,0.86,0.86,0.91,0.94,0.91,0.90,0.88,0.87,0.87,0.86
Col_29,0.47,0.46,0.46,0.47,0.49,0.48,0.48,0.48,0.49,0.49,...,0.49,0.48,0.48,0.50,0.50,0.48,0.48,0.49,0.50,0.51
Col_30,0.38,0.41,0.44,0.47,0.49,0.54,0.52,0.51,0.50,0.50,...,0.65,0.64,0.68,0.71,0.75,0.70,0.69,0.65,0.67,0.68
Col_31,0.30,0.27,0.27,0.28,0.30,0.31,0.28,0.31,0.30,0.30,...,0.34,0.34,0.35,0.36,0.35,0.36,0.36,0.37,0.39,0.41
Col_32,0.57,0.56,0.56,0.56,0.57,0.57,0.57,0.58,0.59,0.59,...,0.61,0.61,0.61,0.62,0.63,0.62,0.63,0.63,0.63,0.62
Col_33,0.76,0.76,0.77,0.78,0.77,0.76,0.77,0.78,0.78,0.78,...,0.73,0.72,0.70,0.72,0.70,0.75,0.76,0.76,0.75,0.76
Col_34,0.85,0.85,0.86,0.86,0.86,0.86,0.87,0.87,0.87,0.87,...,0.86,0.84,0.85,0.85,0.87,0.87,0.87,0.87,0.86,0.85
Col_35,0.57,0.58,0.58,0.59,0.60,0.60,0.62,0.62,0.62,0.62,...,0.58,0.55,0.57,0.57,0.56,0.56,0.56,0.56,0.56,0.57
Col_36,0.56,0.53,0.55,0.56,0.55,0.57,0.62,0.62,0.61,0.61,...,0.61,0.62,0.63,0.63,0.63,0.65,0.65,0.66,0.68,0.68
Col_37,0.33,0.35,0.38,0.38,0.40,0.42,0.42,0.46,0.50,0.49,...,0.46,0.48,0.46,0.46,0.45,0.47,0.46,0.49,0.48,0.46
Col_38,0.39,0.40,0.41,0.41,0.43,0.48,0.46,0.49,0.48,0.48,...,0.54,0.56,0.59,0.59,0.60,0.60,0.60,0.60,0.58,0.58

## 3. Internationalization
### 3.1. For the file (Degree of exposure to international trade total and by product.xlsx)

In [64]:
#Import data using pandas
int_degree_exposure=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Internationalization/Degree of exposure to international trade total and by product.xlsx")
int_degree_exposure

,Years,Total,"Products of agriculture, forestry and fishing",Mining and quarrying,"Food products, beverages and tobacco products","Textiles, wearing apparel and leather products","Wood and paper products, and printing services",Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,1995,26.05,23.6,78.61,30.82,63.81,44.82,54.63,70.46,54.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996,26.01,23.63,77.93,31.03,65.01,44.12,47.53,69.81,59.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997,26.89,26.54,78.6,32.9,67.1,46.42,44.21,71.65,59.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998,27.56,28.39,69.25,34.85,69.28,46.21,44.88,73.7,67.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1999,27.86,26.5,74.58,36.27,71.22,47.34,42.7,75.78,76.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,29.02,28.32,81.51,37.47,72.46,50.73,44.29,79.97,79.03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2001,28.1,30.31,79.53,37.1,73.34,50.09,41.79,78.05,82.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2002,27.82,30.67,79.2,38.6,73.2,52,46.73,79.89,83.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2003,27.87,30.19,81.39,39.02,72.84,52.36,45.74,81.43,84.31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2004,28.43,30.85,85.43,39.73,72.23,52.89,42.16,82.85,84.41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2005,28.32,31.46,88.13,40.95,71.64,52.43,44.2,85.94,84.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2006,30.99,32.73,91.97,44.6,74.89,54.99,45.82,87.49,86.93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2007,31.36,36.44,91.03,46.76,75.91,55.52,46.03,87.2,85.86,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2008,31.58,39.18,91.45,47.66,77.83,56.15,46.17,87.09,87.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2009,28.26,36.69,90.77,47.34,78.31,58.28,56.1,86.6,90.16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,30.71,39.48,93.69,49.67,80.2,60.36,54.69,87.27,90.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2011,32.74,41.14,95.39,52.25,82.33,60.88,58.45,89.43,92.53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2012,34.31,40.65,97.4,52.51,82.36,61.59,59.58,89.96,94.79,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2013,35.84,40.46,98.55,54.7,83.14,64,67.4,92.06,94.54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2014,36.63,40.68,98.06,55.7,84.09,63.92,66.71,92.68,99.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,36.89,41.74,97.48,56.07,83.8,63.8,70.9,92.78,98.16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2016,36.55,42.89,96.36,56.38,84.56,64.61,69.12,93.75,99.93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2017,37.62,43.19,96.14,55.51,84.67,63.51,70.16,92.89,98.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2018,37.93,44.14,96,56.23,84.23,61.86,67.47,93.43,96.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2019,37.98,43.71,96.94,56.27,85.48,62.61,70.72,94.3,98.12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Degree of exposure to international trade: tot...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Data Sources: INE - Annual National Accounts (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Source: PORDATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Last updated: 2022-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,The figures presented by the responsible entit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Symbology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,┴,Series break,Pro,Provisional value,Pre,Preliminary value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,...,Confidential,x,Not available,e,Less than half the unit used,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,//,Not applicable,f,Forecast,§,Extremely unreliable value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,-,Absent value,Rv,Revised value,(R),Data rectified by the relevant body,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,N,Negligible value,s,Estimated value,u,Unreliable or uncertain data,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Data obtained in https:www.pordata.pt in 02-06...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,,,,,,,,,,,...,,,,,,,,,,

In [65]:
#Liste the name of columns
int_degree_exposure.columns

#Delete all rows with data not relevant
int_degree_exposure = int_degree_exposure.drop(labels=range(25, 48), axis=0)

#Delete all columns with NAN values
int_degree_exposure = int_degree_exposure.dropna(thresh=10, axis=1)

#Change the types of data have  to be used in visulizations and database
int_degree_exposure = int_degree_exposure.astype(float)
int_degree_exposure['Years'] = int_degree_exposure['Years'].astype(int)

In [66]:
#Verify that the types of data have changed to be used in visulizations and database
int_degree_exposure.dtypes

Years                                                                                                                                                                         int64
Total                                                                                                                                                                       float64
Products of agriculture, forestry and fishing                                                                                                                               float64
Mining and quarrying                                                                                                                                                        float64
Food products, beverages and tobacco products                                                                                                                               float64
Textiles, wearing apparel and leather products                                                                                                                              float64
Wood and paper products, and printing services                                                                                                                              float64
Coke and refined petroleum products                                                                                                                                         float64
Chemicals and chemical products                                                                                                                                             float64
Basic pharmaceutical products and pharmaceutical preparations                                                                                                               float64
Rubber and plastics products, and other non-metallic mineral products                                                                                                       float64
Basic metals and fabricated metal products, except machinery and equipment                                                                                                  float64
Computer, electronic and optical products                                                                                                                                   float64
Electrical equipment                                                                                                                                                        float64
Machinery and equipment n.e.c.                                                                                                                                              float64
Transport equipment                                                                                                                                                         float64
Furniture, other manufactured goods, repair and installation services of machinery and equipment                                                                            float64
Electricity, gas, steam and air-conditioning                                                                                                                                float64
Water supply, sewerage, waste management and remediation services                                                                                                           float64
Constructions and construction works                                                                                                                                        float64
Wholesale and retail trade services, repair services of motor vehicles and motorcycles                                                                                      float64
Transportation and storage services                                                                                                                                         float64
Accommodation and food services                                                                                                                                             float64
Publishing, audiovisual and broadcasting services                                                                                                                           float64
Telecommunications services                                                                                                                                                 float64
Computer programming, consultancy and related services, information services                                                                                                float64
Financial and insurance services                                                                                                                                            float64
Real estate services                                                                                                                                                        float64
Legal and accounting services, services of head offices, management consulting services, architectural and engineering services, technical testing and analysis services    float64
Scientific research and development services                                                                                                                                float64
Advertising and market research services, other professional, scientific and technical services, veterinary services                                                        float64
Administrative and support services                                                                                                                                         float64
Public administration and defence services, compulsory social security services                                                                                             float64
Education services                                                                                                                                                          float64
Human health services                                                                                                                                                       float64
Social work services                                                                                                                                                        float64
Arts, entertainment and recreation services                                                                                                                                 float64
Other services                                                                                                                                                              float64
Services of households as employers, undifferentiated goods and services produced by households for own use                                                                 float64
dtype: object

In [67]:
#Rename the columns by code "Col_" plus position
int_degree_exposure.columns = ['Col_' + str(i) if 3 <= i <= 39 else x for i, x in enumerate(int_degree_exposure.columns, 1)]

In [68]:
#Delete columns Col_39
int_degree_exposure = int_degree_exposure.drop(labels=['Col_39'], axis=1)

In [69]:
#Transpose
int_degree_exposure = int_degree_exposure.T

#Rename the columns name with the values of the row index 0 
int_degree_exposure.rename(columns=int_degree_exposure.iloc[0], inplace = True)

int_degree_exposure = int_degree_exposure.drop(labels=['Years'], axis=0)
int_degree_exposure = int_degree_exposure.drop(labels=['Total'], axis=0)


cols=range(1995, 2020)
int_degree_exposure.columns=cols

In [70]:
#Export to CSV file
int_degree_exposure.to_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Internationalization/Degree_exposure.csv', index=True)
int_degree_exposure

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Col_3,23.60,23.63,26.54,28.39,26.50,28.32,30.31,30.67,30.19,30.85,...,39.48,41.14,40.65,40.46,40.68,41.74,42.89,43.19,44.14,43.71
Col_4,78.61,77.93,78.60,69.25,74.58,81.51,79.53,79.20,81.39,85.43,...,93.69,95.39,97.40,98.55,98.06,97.48,96.36,96.14,96.00,96.94
Col_5,30.82,31.03,32.90,34.85,36.27,37.47,37.10,38.60,39.02,39.73,...,49.67,52.25,52.51,54.70,55.70,56.07,56.38,55.51,56.23,56.27
Col_6,63.81,65.01,67.10,69.28,71.22,72.46,73.34,73.20,72.84,72.23,...,80.20,82.33,82.36,83.14,84.09,83.80,84.56,84.67,84.23,85.48
Col_7,44.82,44.12,46.42,46.21,47.34,50.73,50.09,52.00,52.36,52.89,...,60.36,60.88,61.59,64.00,63.92,63.80,64.61,63.51,61.86,62.61
Col_8,54.63,47.53,44.21,44.88,42.70,44.29,41.79,46.73,45.74,42.16,...,54.69,58.45,59.58,67.40,66.71,70.90,69.12,70.16,67.47,70.72
Col_9,70.46,69.81,71.65,73.70,75.78,79.97,78.05,79.89,81.43,82.85,...,87.27,89.43,89.96,92.06,92.68,92.78,93.75,92.89,93.43,94.30
Col_10,54.25,59.71,59.96,67.45,76.10,79.03,82.71,83.09,84.31,84.41,...,90.10,92.53,94.79,94.54,99.01,98.16,99.93,98.74,96.15,98.12
Col_11,40.28,41.79,43.34,44.96,45.77,47.86,47.75,49.69,52.67,55.17,...,66.25,69.94,75.27,78.91,79.47,79.63,79.88,78.46,78.22,76.94
Col_12,50.85,52.27,53.38,56.78,59.53,63.85,62.60,66.43,75.06,74.26,...,73.07,77.24,82.84,81.64,80.18,78.89,77.51,77.71,75.90,75.62
Col_13,88.63,86.17,88.48,93.24,93.73,95.10,98.45,97.11,98.86,99.87,...,99.64,100.00,99.88,99.23,98.17,98.89,98.74,98.56,98.81,94.18
Col_14,90.87,90.87,96.14,98.97,95.81,95.17,91.40,91.88,94.00,95.26,...,94.57,96.80,99.90,99.83,99.94,99.89,99.83,99.73,99.19,99.17
Col_15,74.04,77.41,77.99,79.44,80.99,82.46,81.57,79.97,82.99,86.58,...,90.55,94.60,99.48,99.59,98.76,99.08,98.73,99.05,99.35,98.12
Col_16,83.62,86.31,85.17,87.80,91.22,92.86,93.64,94.88,95.40,95.53,...,97.29,96.59,96.50,96.55,97.01,97.70,97.02,96.06,96.14,97.87
Col_17,44.47,43.23,43.03,45.49,43.94,46.35,49.92,51.06,50.87,54.44,...,59.15,64.33,64.30,70.98,69.97,69.04,71.52,72.84,71.59,73.26
Col_18,0.36,0.63,1.23,0.35,1.01,1.22,3.16,5.04,3.72,5.09,...,1.96,2.31,2.87,2.70,2.55,2.38,2.35,3.00,3.06,3.21
Col_19,7.98,5.73,6.64,6.67,6.97,8.71,8.01,8.84,9.83,14.73,...,18.47,21.94,21.34,20.78,21.33,19.14,18.51,21.52,23.49,19.91
Col_20,2.05,2.06,1.64,1.10,1.10,0.80,0.98,1.08,1.38,1.50,...,2.03,2.60,3.29,4.19,3.87,3.90,5.05,4.82,4.50,4.58
Col_21,1.54,1.21,1.12,1.11,1.28,1.14,1.00,0.80,0.85,0.95,...,1.43,1.27,1.22,1.05,1.46,1.49,1.77,1.99,2.11,2.34
Col_22,27.86,24.83,25.20,26.10,24.71,25.54,25.38,25.68,25.61,25.17,...,31.83,34.32,36.98,40.64,41.95,39.22,38.70,41.29,42.62,42.15
Col_23,6.47,6.62,6.64,7.24,7.16,7.74,7.52,7.11,6.87,6.91,...,7.83,8.18,7.85,8.47,8.68,8.96,7.92,7.64,7.16,7.34
Col_24,21.21,20.26,21.88,23.43,23.71,24.86,26.19,24.98,25.41,26.63,...,27.05,27.76,31.18,27.64,30.33,30.36,31.47,27.90,28.16,28.16
Col_25,11.02,8.39,8.71,6.67,5.31,5.82,5.35,6.18,7.18,8.05,...,11.08,12.55,13.39,13.89,16.33,19.11,14.01,12.37,13.30,10.71
Col_26,12.14,9.64,9.91,11.53,14.56,13.96,12.23,13.24,13.22,12.29,...,18.72,22.91,23.84,26.18,29.80,32.27,34.79,35.15,37.07,39.21
Col_27,14.54,11.86,10.79,9.28,10.52,11.57,5.34,6.29,6.26,7.06,...,7.80,7.20,8.22,7.64,7.87,8.29,8.18,8.30,8.70,9.70
Col_28,0.17,0.18,0.19,0.18,0.19,0.22,0.19,0.15,0.14,0.14,...,0.17,0.15,0.18,0.17,0.17,0.20,0.16,0.16,0.07,0.07
Col_29,8.59,6.91,7.69,8.27,6.92,6.55,5.92,7.03,6.55,7.23,...,12.75,14.12,15.23,15.29,15.45,17.55,16.40,17.01,15.40,15.44
Col_30,20.93,16.62,13.63,17.92,13.88,15.46,12.90,16.59,17.19,13.78,...,15.56,16.78,14.63,24.56,29.19,30.91,36.00,35.68,40.56,38.06
Col_31,15.82,12.89,15.13,17.49,15.85,13.99,12.81,14.91,13.59,13.39,...,31.88,34.29,37.91,42.64,46.33,47.83,50.49,51.59,49.16,46.98
Col_32,16.18,12.99,14.18,15.65,15.11,14.22,17.29,19.74,18.53,19.44,...,24.44,21.56,21.52,26.56,31.09,29.57,29.83,29.14,27.28,29.11
Col_33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.24,0.26,0.27,0.29
Col_34,0.06,0.07,0.06,0.07,0.06,0.06,0.05,0.04,0.04,0.03,...,0.02,0.02,0.03,0.98,0.50,0.55,0.53,0.51,0.49,0.48
Col_35,0.09,0.09,0.09,0.09,0.09,0.10,0.08,0.06,0.06,0.05,...,0.03,0.03,0.04,1.07,0.52,0.50,0.53,0.59,0.56,0.60
Col_36,0.07,0.08,0.08,0.09,0.10,0.10,0.09,0.07,0.07,0.07,...,0.05,0.04,0.05,0.03,0.03,0.03,0.02,0.02,0.02,0.02
Col_37,6.27,5.23,6.19,8.45,6.71,7.45,7.58,6.70,6.39,7.17,...,8.58,8.41,10.56,12.33,6.14,5.35,5.67,6.09,5.63,5.73
Col_38,0.17,0.18,0.18,0.19,0.21,0.22,0.19,0.15,0.14,0.13,...,0.08,0.07,0.10,0.10,0.08,0.08,0.24,0.29,0.35,0.34

### 3.2  For the file (Export intensity total and by product.xlsx)

In [71]:
#Import data using pandas
int_export_intensity=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Internationalization/Export intensity total and by product.xlsx")
int_export_intensity

,Years,Total,"Products of agriculture, forestry and fishing",Mining and quarrying,"Food products, beverages and tobacco products","Textiles, wearing apparel and leather products","Wood and paper products, and printing services",Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,1995,12.11,3.47,29.65,11.54,47.32,33.71,33.94,29.04,13.76,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996,11.98,3.32,26.46,11.71,48.04,32.09,25,28.39,17.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997,12.28,4.63,25.85,12.69,49.51,33.98,23.36,31.01,17.88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998,12.33,4.53,18.12,12.86,50.82,32.98,22.52,31.01,21.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1999,12.24,4.6,17.21,13.1,52.91,33.29,19.74,32.95,26.15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,12.8,5.44,17.45,14.42,53.18,36.31,18.73,38.89,31.56,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2001,12.37,6.66,15.06,13.89,53.95,35.04,15.58,35.61,32.79,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2002,12.6,7.26,15.97,15.28,53.64,36.87,18.76,37.92,33.84,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2003,13.03,7.9,16.62,15.6,53.46,37.68,21.32,40.96,32.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2004,13.04,8.56,24.64,15.94,52,37.63,20.24,43.88,30.74,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2005,12.82,8.96,27.63,17.26,50.81,37.21,21.14,48.63,31.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2006,14.63,9.84,40.43,19.5,53.62,39.77,25.98,50.94,35.34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2007,14.89,10.6,38.85,21.78,54.33,40.03,23.76,52.57,36.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2008,14.66,12.53,28.31,22.76,56.77,40.28,24.15,52.55,38.26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2009,13.14,12.14,37.64,22.41,56.71,42.47,32.5,49.97,44.77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,14.44,13.24,44.07,23.93,58.67,45.16,33.6,53.44,45.28,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2011,16.41,13.6,48.19,26.01,61.99,46.43,36.24,56.58,58.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2012,18.11,14.03,57.52,26.88,62.95,49.11,41.47,56.59,64.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2013,19.34,13.51,68.82,28.88,63.84,51.7,51.23,59.93,64.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2014,19.52,14.95,63.33,30.18,64.68,50.9,45.84,61.19,84.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,19.71,15.61,61.07,30.13,64.37,51.1,53.75,61.91,80.77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2016,19.49,16.35,57.66,30.46,65.17,51.5,50.62,64.24,99.36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2017,19.95,16.97,51.81,29.53,65.26,50.13,51.9,61.46,88.59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2018,19.97,17.6,51.48,30.01,64.49,48.67,48.12,62.44,77.12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2019,19.97,18.43,59.62,29.79,65.77,49.42,48.13,65.49,82.52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Export intensity: total and by product,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Data Sources: INE - Annual National Accounts (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Source: PORDATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Last updated: 2021-09-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,The figures presented by the responsible entit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Symbology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,┴,Series break,Pro,Provisional value,Pre,Preliminary value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,...,Confidential,x,Not available,e,Less than half the unit used,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,//,Not applicable,f,Forecast,§,Extremely unreliable value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,-,Absent value,Rv,Revised value,(R),Data rectified by the relevant body,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,N,Negligible value,s,Estimated value,u,Unreliable or uncertain data,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Data obtained in https:www.pordata.pt in 02-06...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,,,,,,,,,,,...,,,,,,,,,,

In [72]:
#Liste the name of columns
int_export_intensity.columns

#Delete all rows with data not relevant
int_export_intensity = int_export_intensity.drop(labels=range(25, 48), axis=0)

#Delete all columns with NAN values
int_export_intensity = int_export_intensity.dropna(thresh=10, axis=1)

#Change the types of data have  to be used in visulizations and database
int_export_intensity = int_export_intensity.astype(float)
int_export_intensity['Years'] = int_export_intensity['Years'].astype(int)

In [73]:
#Verify that the types of data have changed to be used in visulizations and database
int_export_intensity.dtypes

Years                                                                                                                                                                         int64
Total                                                                                                                                                                       float64
Products of agriculture, forestry and fishing                                                                                                                               float64
Mining and quarrying                                                                                                                                                        float64
Food products, beverages and tobacco products                                                                                                                               float64
Textiles, wearing apparel and leather products                                                                                                                              float64
Wood and paper products, and printing services                                                                                                                              float64
Coke and refined petroleum products                                                                                                                                         float64
Chemicals and chemical products                                                                                                                                             float64
Basic pharmaceutical products and pharmaceutical preparations                                                                                                               float64
Rubber and plastics products, and other non-metallic mineral products                                                                                                       float64
Basic metals and fabricated metal products, except machinery and equipment                                                                                                  float64
Computer, electronic and optical products                                                                                                                                   float64
Electrical equipment                                                                                                                                                        float64
Machinery and equipment n.e.c.                                                                                                                                              float64
Transport equipment                                                                                                                                                         float64
Furniture, other manufactured goods, repair and installation services of machinery and equipment                                                                            float64
Electricity, gas, steam and air-conditioning                                                                                                                                float64
Water supply, sewerage, waste management and remediation services                                                                                                           float64
Constructions and construction works                                                                                                                                        float64
Wholesale and retail trade services, repair services of motor vehicles and motorcycles                                                                                      float64
Transportation and storage services                                                                                                                                         float64
Accommodation and food services                                                                                                                                             float64
Publishing, audiovisual and broadcasting services                                                                                                                           float64
Telecommunications services                                                                                                                                                 float64
Computer programming, consultancy and related services, information services                                                                                                float64
Financial and insurance services                                                                                                                                            float64
Real estate services                                                                                                                                                        float64
Legal and accounting services, services of head offices, management consulting services, architectural and engineering services, technical testing and analysis services    float64
Scientific research and development services                                                                                                                                float64
Advertising and market research services, other professional, scientific and technical services, veterinary services                                                        float64
Administrative and support services                                                                                                                                         float64
Public administration and defence services, compulsory social security services                                                                                             float64
Education services                                                                                                                                                          float64
Human health services                                                                                                                                                       float64
Social work services                                                                                                                                                        float64
Arts, entertainment and recreation services                                                                                                                                 float64
Other services                                                                                                                                                              float64
Services of households as employers, undifferentiated goods and services produced by households for own use                                                                 float64
dtype: object

In [74]:
#Rename the columns by code "Col_" plus position
int_export_intensity.columns = ['Col_' + str(i) if 3 <= i <= 39 else x for i, x in enumerate(int_export_intensity.columns, 1)]

In [75]:
#Delete columns Col_39
int_export_intensity = int_export_intensity.drop(labels=['Col_39'], axis=1)

In [76]:
#Transpose
int_export_intensity = int_export_intensity.T

#Rename the columns name with the values of the row index 0 
int_export_intensity.rename(columns=int_export_intensity.iloc[0], inplace = True)

int_export_intensity = int_export_intensity.drop(labels=['Years'], axis=0)
int_export_intensity = int_export_intensity.drop(labels=['Total'], axis=0)

cols=range(1995, 2020)
int_export_intensity.columns=cols

In [77]:
#Export to CSV file
int_export_intensity.to_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Internationalization/export_intensity.csv', index=True)
int_export_intensity

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Col_3,3.47,3.32,4.63,4.53,4.60,5.44,6.66,7.26,7.90,8.56,...,13.24,13.60,14.03,13.51,14.95,15.61,16.35,16.97,17.60,18.43
Col_4,29.65,26.46,25.85,18.12,17.21,17.45,15.06,15.97,16.62,24.64,...,44.07,48.19,57.52,68.82,63.33,61.07,57.66,51.81,51.48,59.62
Col_5,11.54,11.71,12.69,12.86,13.10,14.42,13.89,15.28,15.60,15.94,...,23.93,26.01,26.88,28.88,30.18,30.13,30.46,29.53,30.01,29.79
Col_6,47.32,48.04,49.51,50.82,52.91,53.18,53.95,53.64,53.46,52.00,...,58.67,61.99,62.95,63.84,64.68,64.37,65.17,65.26,64.49,65.77
Col_7,33.71,32.09,33.98,32.98,33.29,36.31,35.04,36.87,37.68,37.63,...,45.16,46.43,49.11,51.70,50.90,51.10,51.50,50.13,48.67,49.42
Col_8,33.94,25.00,23.36,22.52,19.74,18.73,15.58,18.76,21.32,20.24,...,33.60,36.24,41.47,51.23,45.84,53.75,50.62,51.90,48.12,48.13
Col_9,29.04,28.39,31.01,31.01,32.95,38.89,35.61,37.92,40.96,43.88,...,53.44,56.58,56.59,59.93,61.19,61.91,64.24,61.46,62.44,65.49
Col_10,13.76,17.60,17.88,21.35,26.15,31.56,32.79,33.84,32.66,30.74,...,45.28,58.29,64.97,64.09,84.20,80.77,99.36,88.59,77.12,82.52
Col_11,23.21,23.12,23.83,24.47,24.73,26.32,26.22,27.98,31.68,34.50,...,46.92,51.67,58.80,62.46,63.06,62.92,61.87,59.92,59.21,56.94
Col_12,19.99,22.32,22.45,25.52,28.37,31.60,30.72,36.15,47.72,45.35,...,45.19,51.32,59.82,59.67,58.46,55.79,54.31,53.87,51.50,50.85
Col_13,55.58,50.77,53.28,62.37,64.39,68.04,78.78,74.93,80.90,92.11,...,89.39,100.25,103.61,111.53,115.37,118.35,113.52,108.90,105.33,119.93
Col_14,70.01,68.97,82.64,92.96,80.21,80.57,72.03,70.54,74.98,75.06,...,78.86,83.15,94.62,93.20,95.87,93.52,92.16,90.73,87.66,85.94
Col_15,28.61,33.08,32.45,34.02,37.60,40.18,39.99,40.21,49.99,54.78,...,62.98,75.64,96.44,98.32,93.67,94.09,90.51,90.78,91.12,85.51
Col_16,57.34,62.75,59.49,62.31,67.31,71.18,72.76,76.85,79.04,78.23,...,83.63,84.99,88.66,87.98,86.95,88.86,87.47,85.05,85.56,91.08
Col_17,18.03,16.76,16.29,17.12,14.86,16.45,20.13,20.52,21.90,23.77,...,27.01,33.09,35.20,41.98,39.89,38.02,39.63,40.62,39.81,40.46
Col_18,0.03,0.05,0.03,0.04,0.66,0.53,1.55,2.52,1.06,0.63,...,0.59,0.67,0.19,0.94,1.15,0.79,1.76,1.94,1.97,1.07
Col_19,4.90,3.79,4.65,4.11,4.18,5.86,5.64,5.99,6.31,8.30,...,11.31,12.46,12.21,10.34,9.95,9.25,9.53,10.87,11.03,9.91
Col_20,0.97,1.07,0.97,0.68,0.62,0.55,0.67,0.70,0.90,1.08,...,1.66,2.07,2.67,3.39,3.12,3.14,4.09,3.95,3.66,3.22
Col_21,0.87,0.60,0.62,0.69,0.73,0.61,0.54,0.39,0.45,0.44,...,0.85,0.76,0.62,0.61,0.83,0.87,0.93,0.97,0.94,1.01
Col_22,21.72,19.04,19.53,20.61,18.90,19.32,19.37,20.22,20.34,20.10,...,26.65,29.24,30.97,33.04,32.85,31.08,30.91,33.14,34.50,33.82
Col_23,3.69,3.55,3.64,4.02,3.90,4.18,4.20,3.97,3.80,3.77,...,4.05,4.32,4.40,4.81,5.00,5.16,4.32,4.00,3.38,3.40
Col_24,4.62,4.35,5.41,5.38,5.25,6.25,6.58,6.29,6.27,7.40,...,9.27,9.75,12.65,9.65,11.58,10.57,10.49,9.24,8.59,9.23
Col_25,7.41,5.45,5.64,3.85,3.19,3.18,2.98,3.45,4.32,4.68,...,6.17,7.19,7.93,8.21,9.24,10.73,8.23,6.94,8.37,6.40
Col_26,3.07,2.27,2.56,2.76,3.84,4.22,3.28,3.57,3.98,4.56,...,7.47,9.89,12.27,13.50,15.46,17.99,20.50,22.30,23.61,27.05
Col_27,7.22,5.24,5.09,5.27,7.08,7.82,3.11,3.03,2.78,3.23,...,2.68,2.72,3.81,3.55,3.35,3.63,3.66,3.85,4.22,4.48
Col_28,0.05,0.05,0.05,0.06,0.05,0.08,0.09,0.08,0.08,0.08,...,0.10,0.10,0.12,0.13,0.12,0.11,0.11,0.11,0.02,0.02
Col_29,2.65,1.99,2.19,1.98,2.16,2.25,2.43,3.36,3.03,3.46,...,7.60,9.21,9.94,9.84,9.54,10.34,9.94,10.06,8.79,9.23
Col_30,3.28,2.38,2.17,3.11,1.93,1.55,1.51,2.80,2.24,1.93,...,1.51,1.72,1.80,3.48,4.72,5.12,5.85,5.79,6.47,7.02
Col_31,4.23,3.30,3.59,2.93,4.13,3.54,4.25,5.05,4.54,5.00,...,13.00,14.21,15.16,16.58,16.91,17.33,18.18,18.82,18.18,17.46
Col_32,3.99,3.03,3.03,3.58,3.79,3.97,6.15,6.96,6.83,8.00,...,8.52,7.70,7.86,11.73,12.50,11.83,10.36,11.16,10.86,10.86
Col_33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.28,0.29,0.31,0.33
Col_34,0.01,0.01,0.01,0.01,0.01,0.02,0.02,0.02,0.02,0.02,...,0.01,0.01,0.02,0.51,0.34,0.36,0.35,0.34,0.33,0.31
Col_35,0.02,0.02,0.02,0.03,0.02,0.03,0.04,0.03,0.03,0.02,...,0.02,0.02,0.03,0.47,0.31,0.26,0.29,0.37,0.33,0.33
Col_36,0.03,0.03,0.03,0.04,0.05,0.05,0.05,0.05,0.05,0.05,...,0.04,0.03,0.04,0.02,0.02,0.01,0.01,0.01,0.01,0.01
Col_37,3.00,2.32,2.84,3.72,2.83,3.51,3.79,2.99,3.03,3.12,...,3.68,3.58,4.62,5.73,3.75,3.10,3.33,4.06,3.37,3.27
Col_38,0.04,0.04,0.04,0.06,0.06,0.08,0.08,0.08,0.07,0.07,...,0.05,0.05,0.07,0.07,0.05,0.04,0.19,0.24,0.29,0.28

### 3.3 For the file (Import penetration rate in the domestic market total and by product.xlsx)

In [78]:
#Import data using pandas
int_import_penetracion=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Internationalization/Import penetration rate in the domestic market total and by product.xlsx")
int_import_penetracion

,Years,Total,"Products of agriculture, forestry and fishing",Mining and quarrying,"Food products, beverages and tobacco products","Textiles, wearing apparel and leather products","Wood and paper products, and printing services",Coke and refined petroleum products,Chemicals and chemical products,Basic pharmaceutical products and pharmaceutical preparations,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,1995,15.87,22.2,71.54,20.7,28.42,17.69,37.43,55.01,43.41,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996,15.93,22.25,72.19,20.78,29.68,18.76,34.34,55.89,48.07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1997,16.65,24.68,73.13,22.05,32.02,19.95,31.07,56.62,48.65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998,17.37,26.48,64.63,24.15,35.26,20.91,33.89,59.16,51.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1999,17.8,24.52,71.31,25.56,37.19,22.17,32.57,61.02,60.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2000,18.6,25.85,79.19,25.85,39.5,23.74,33.92,63.47,61.01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2001,17.95,27.31,76.81,25.93,40.86,24.38,33.39,63.61,63.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2002,17.41,26.94,77.15,26.25,41.1,25.43,37.63,64.9,67.29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2003,17.06,26.36,79.64,26.49,41.26,25.15,34.39,65.03,68.93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2004,17.69,26.35,82.54,26.91,41.47,26.12,30.27,65.35,69.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2005,17.78,26.85,85.71,27.18,41.22,25.95,31.49,67.51,69.37,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2006,19.16,27.63,88.51,29.61,45.26,27.21,29,69.22,73.54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2007,19.36,31.36,86.36,30.88,46.83,28.14,31.37,69.52,71.62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2008,19.83,33.13,89.06,31.35,50.12,28.78,30.61,70.45,73.52,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2009,17.41,30.25,86.74,31.53,51.51,30.54,37.75,71.87,77.48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2010,19.01,32.54,89.92,32.78,54.08,30.95,33.56,72.4,78.14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2011,19.53,34.01,92.23,34.38,55.04,30.75,37.25,72.9,82.89,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2012,19.79,33.16,94.65,33.45,53.83,30.12,34.14,72.53,84.99,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2013,20.46,33.28,96.15,34.42,55.47,31.86,38.18,73.85,83.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2014,21.25,32.54,95.02,34.67,56.92,32.4,41.81,75.96,92.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2015,21.4,33.56,93.75,35.2,57.37,32.13,42.01,77.48,91.47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2016,21.19,34.37,91.61,35.89,57.81,33.32,40.52,79.6,99.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2017,22.07,34.32,91.63,35.99,58.34,33.01,41.6,77.97,94.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2018,22.45,35,91.73,36.62,57.83,32.05,40.85,79.6,90.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2019,22.51,34.11,92.47,36.91,60.25,32.86,46.47,81.3,91.85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Import penetration rate in the domestic market...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Data Sources: INE - Annual National Accounts (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Source: PORDATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Last updated: 2021-09-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,The figures presented by the responsible entit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Symbology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,┴,Series break,Pro,Provisional value,Pre,Preliminary value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,...,Confidential,x,Not available,e,Less than half the unit used,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,//,Not applicable,f,Forecast,§,Extremely unreliable value,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,-,Absent value,Rv,Revised value,(R),Data rectified by the relevant body,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,N,Negligible value,s,Estimated value,u,Unreliable or uncertain data,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Data obtained in https:www.pordata.pt in 02-06...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,,,,,,,,,,,...,,,,,,,,,,

In [79]:
#Liste the name of columns
int_import_penetracion.columns

#Delete all rows with data not relevant
int_import_penetracion = int_import_penetracion.drop(labels=range(25, 48), axis=0)

#Delete all columns with NAN values
int_import_penetracion = int_import_penetracion.dropna(thresh=10, axis=1)

#Change the types of data have  to be used in visulizations and database
int_import_penetracion = int_import_penetracion.astype(float)
int_import_penetracion['Years'] = int_import_penetracion['Years'].astype(int)

In [80]:
#Verify that the types of data have changed to be used in visulizations and database
int_import_penetracion.dtypes

Years                                                                                                                                                                         int64
Total                                                                                                                                                                       float64
Products of agriculture, forestry and fishing                                                                                                                               float64
Mining and quarrying                                                                                                                                                        float64
Food products, beverages and tobacco products                                                                                                                               float64
Textiles, wearing apparel and leather products                                                                                                                              float64
Wood and paper products, and printing services                                                                                                                              float64
Coke and refined petroleum products                                                                                                                                         float64
Chemicals and chemical products                                                                                                                                             float64
Basic pharmaceutical products and pharmaceutical preparations                                                                                                               float64
Rubber and plastics products, and other non-metallic mineral products                                                                                                       float64
Basic metals and fabricated metal products, except machinery and equipment                                                                                                  float64
Computer, electronic and optical products                                                                                                                                   float64
Electrical equipment                                                                                                                                                        float64
Machinery and equipment n.e.c.                                                                                                                                              float64
Transport equipment                                                                                                                                                         float64
Furniture, other manufactured goods, repair and installation services of machinery and equipment                                                                            float64
Electricity, gas, steam and air-conditioning                                                                                                                                float64
Water supply, sewerage, waste management and remediation services                                                                                                           float64
Constructions and construction works                                                                                                                                        float64
Wholesale and retail trade services, repair services of motor vehicles and motorcycles                                                                                      float64
Transportation and storage services                                                                                                                                         float64
Accommodation and food services                                                                                                                                             float64
Publishing, audiovisual and broadcasting services                                                                                                                           float64
Telecommunications services                                                                                                                                                 float64
Computer programming, consultancy and related services, information services                                                                                                float64
Financial and insurance services                                                                                                                                            float64
Real estate services                                                                                                                                                        float64
Legal and accounting services, services of head offices, management consulting services, architectural and engineering services, technical testing and analysis services    float64
Scientific research and development services                                                                                                                                float64
Advertising and market research services, other professional, scientific and technical services, veterinary services                                                        float64
Administrative and support services                                                                                                                                         float64
Public administration and defence services, compulsory social security services                                                                                             float64
Education services                                                                                                                                                          float64
Human health services                                                                                                                                                       float64
Social work services                                                                                                                                                        float64
Arts, entertainment and recreation services                                                                                                                                 float64
Other services                                                                                                                                                              float64
Services of households as employers, undifferentiated goods and services produced by households for own use                                                                 float64
dtype: object

In [81]:
#Rename the columns by code "Col_" plus position
int_import_penetracion.columns = ['Col_' + str(i) if 3 <= i <= 39 else x for i, x in enumerate(int_import_penetracion.columns, 1)]

In [82]:
#Delete columns Col_39
int_import_penetracion = int_import_penetracion.drop(labels=['Col_39'], axis=1)

In [83]:
#Transpose
int_import_penetracion = int_import_penetracion.T

#Rename the columns name with the values of the row index 0 
int_import_penetracion.rename(columns=int_import_penetracion.iloc[0], inplace = True)
int_import_penetracion

int_import_penetracion = int_import_penetracion.drop(labels=['Years'], axis=0)
int_import_penetracion = int_import_penetracion.drop(labels=['Total'], axis=0)


cols=range(1995, 2020)
int_import_penetracion.columns=cols

In [84]:
#Export to CSV file
int_import_penetracion.to_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project4/Data_Economic_Activities/Internationalization/import_penetracion.csv', index=True)
int_import_penetracion

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Col_3,22.20,22.25,24.68,26.48,24.52,25.85,27.31,26.94,26.36,26.35,...,32.54,34.01,33.16,33.28,32.54,33.56,34.37,34.32,35.00,34.11
Col_4,71.54,72.19,73.13,64.63,71.31,79.19,76.81,77.15,79.64,82.54,...,89.92,92.23,94.65,96.15,95.02,93.75,91.61,91.63,91.73,92.47
Col_5,20.70,20.78,22.05,24.15,25.56,25.85,25.93,26.25,26.49,26.91,...,32.78,34.38,33.45,34.42,34.67,35.20,35.89,35.99,36.62,36.91
Col_6,28.42,29.68,32.02,35.26,37.19,39.50,40.86,41.10,41.26,41.47,...,54.08,55.04,53.83,55.47,56.92,57.37,57.81,58.34,57.83,60.25
Col_7,17.69,18.76,19.95,20.91,22.17,23.74,24.38,25.43,25.15,26.12,...,30.95,30.75,30.12,31.86,32.40,32.13,33.32,33.01,32.05,32.86
Col_8,37.43,34.34,31.07,33.89,32.57,33.92,33.39,37.63,34.39,30.27,...,33.56,37.25,34.14,38.18,41.81,42.01,40.52,41.60,40.85,46.47
Col_9,55.01,55.89,56.62,59.16,61.02,63.47,63.61,64.90,65.03,65.35,...,72.40,72.90,72.53,73.85,75.96,77.48,79.60,77.97,79.60,81.30
Col_10,43.41,48.07,48.65,51.89,60.29,61.01,63.11,67.29,68.93,69.60,...,78.14,82.89,84.99,83.75,92.96,91.47,99.71,94.75,90.06,91.85
Col_11,22.72,24.79,26.14,27.65,28.41,29.80,29.80,30.79,31.59,32.47,...,39.14,40.82,44.00,47.58,49.00,49.08,49.37,48.57,49.14,48.60
Col_12,38.13,38.40,39.64,41.72,43.56,47.08,46.14,47.83,52.32,53.02,...,52.16,53.20,55.62,57.11,56.61,56.32,54.37,55.53,54.34,54.29
Col_13,71.34,69.55,71.83,80.32,81.35,83.48,88.79,86.26,88.75,95.63,...,95.17,100.13,101.88,105.74,107.32,108.47,106.99,105.03,103.02,111.12
Col_14,76.68,77.37,86.86,94.38,84.60,85.83,80.21,79.09,81.99,82.49,...,82.54,84.68,94.03,92.33,95.44,93.00,92.47,91.41,90.09,89.40
Col_15,67.26,71.19,71.64,73.01,73.53,74.69,73.98,70.81,74.11,77.22,...,80.97,85.98,97.44,98.81,95.71,96.27,94.07,94.74,95.07,92.69
Col_16,67.79,67.91,67.56,72.13,78.21,79.99,79.94,81.21,82.20,83.47,...,89.37,86.38,87.38,87.92,88.28,90.46,90.00,88.04,87.64,91.75
Col_17,20.10,20.39,21.07,22.87,23.66,25.10,27.62,29.02,30.24,31.74,...,35.52,38.37,35.81,39.60,39.27,38.79,41.12,41.47,40.25,41.63
Col_18,0.34,0.61,1.23,0.33,0.39,0.74,1.79,2.79,2.80,4.68,...,1.44,1.71,2.77,1.85,1.44,1.62,0.61,1.09,1.10,2.19
Col_19,3.56,2.20,2.32,2.89,3.00,3.36,2.66,3.24,3.90,7.29,...,8.86,12.23,12.07,12.39,12.67,11.00,9.95,11.93,13.47,10.59
Col_20,1.03,0.95,0.64,0.40,0.46,0.23,0.28,0.37,0.46,0.40,...,0.31,0.42,0.49,0.64,0.60,0.57,0.73,0.68,0.64,1.19
Col_21,0.81,0.72,0.59,0.52,0.67,0.62,0.54,0.47,0.47,0.60,...,0.72,0.63,0.72,0.55,0.78,0.77,1.02,1.24,1.40,1.59
Col_22,9.10,8.21,8.38,8.40,8.50,9.05,8.83,8.55,8.07,7.60,...,8.80,8.93,10.05,12.13,14.31,13.60,12.71,13.79,14.10,14.11
Col_23,2.93,3.23,3.18,3.47,3.51,3.83,3.58,3.36,3.30,3.35,...,4.04,4.10,3.62,3.84,3.87,4.01,3.66,3.71,3.84,4.00
Col_24,16.96,16.27,17.02,18.70,19.10,19.13,20.31,19.31,19.69,20.54,...,19.92,20.21,21.49,20.44,22.12,22.85,23.74,20.62,21.64,21.46
Col_25,4.64,3.66,3.84,3.38,2.55,3.10,2.71,3.06,3.27,3.85,...,5.79,6.50,6.61,6.93,8.48,10.23,7.03,6.51,6.15,5.10
Col_26,7.89,6.34,6.29,7.54,9.76,8.72,7.96,8.56,8.11,6.63,...,9.89,11.58,10.06,11.39,13.80,13.75,14.66,13.57,14.80,14.39
Col_27,8.37,7.42,6.41,4.64,4.19,4.57,2.53,3.64,3.89,4.32,...,5.74,5.04,5.10,4.75,5.20,5.36,5.24,5.16,5.23,6.07
Col_28,0.12,0.13,0.14,0.12,0.13,0.14,0.10,0.07,0.06,0.06,...,0.06,0.05,0.05,0.04,0.05,0.08,0.05,0.05,0.05,0.05
Col_29,4.85,3.96,4.51,5.06,3.60,3.22,2.55,2.56,2.53,2.63,...,3.75,3.49,3.66,3.74,4.80,5.82,5.18,5.72,5.47,5.17
Col_30,4.86,3.87,2.77,2.97,2.56,3.23,2.37,2.53,3.58,2.75,...,2.56,2.51,2.16,3.98,5.70,5.74,7.07,6.16,7.53,5.83
Col_31,7.75,6.17,7.66,10.06,7.51,6.74,4.92,5.36,5.05,4.43,...,9.31,9.54,9.91,11.65,14.12,14.81,16.31,16.82,16.22,15.35
Col_32,9.08,7.31,8.32,9.01,8.34,7.36,7.78,9.02,8.09,7.63,...,11.71,9.76,9.27,9.87,13.82,13.34,15.36,14.36,13.48,15.53
Col_33,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Col_34,0.06,0.06,0.05,0.06,0.05,0.05,0.04,0.03,0.02,0.02,...,0.01,0.01,0.01,0.56,0.21,0.24,0.23,0.22,0.22,0.21
Col_35,0.07,0.07,0.07,0.06,0.07,0.07,0.05,0.03,0.03,0.03,...,0.01,0.01,0.01,0.61,0.22,0.25,0.24,0.22,0.23,0.27
Col_36,0.05,0.05,0.06,0.05,0.06,0.06,0.04,0.03,0.03,0.03,...,0.01,0.01,0.01,0.01,0.01,0.02,0.01,0.01,0.01,0.01
Col_37,3.52,3.10,3.60,5.13,4.16,4.26,4.13,3.96,3.63,4.36,...,5.51,5.42,6.69,7.58,2.78,2.61,2.63,2.34,2.53,2.74
Col_38,0.12,0.12,0.12,0.12,0.13,0.13,0.09,0.07,0.05,0.05,...,0.02,0.02,0.02,0.02,0.02,0.03,0.02,0.02,0.02,0.02

## Coding Names

In [85]:
#Import coding names data using pandas
encd_name=pd.read_excel(r"/Users/edgartome_1/IronHack/IronProjects/Project4/SQL/Encondig Columns.xlsx")
encd_name

    Unnamed: 0 Unnamed: 1                                   Encondig Columns
0          NaN        NaN                                                NaN
1          NaN      Col_3       Products of agriculture forestry and fishing
2          NaN      Col_4                               Mining and quarrying
3          NaN      Col_5       Food products beverages and tobacco products
4          NaN      Col_6      Textiles wearing apparel and leather products
5          NaN      Col_7      Wood and paper products and printing services
6          NaN      Col_8                Coke and refined petroleum products
7          NaN      Col_9                    Chemicals and chemical products
8          NaN     Col_10  Basic pharmaceutical products and pharmaceutic...
9          NaN     Col_11  Rubber and plastics products and other non-met...
10         NaN     Col_12  Basic metals and fabricated metal products exc...
11         NaN     Col_13           Computer electronic and optical products
12         NaN     Col_14                               Electrical equipment
13         NaN     Col_15                            Machinery and equipment
14         NaN     Col_16                                Transport equipment
15         NaN     Col_17  Furniture other manufactured goods repair and ...
16         NaN     Col_18         Electricity gas steam and air-conditioning
17         NaN     Col_19  Water supply sewerage waste management and rem...
18         NaN     Col_20               Constructions and construction works
19         NaN     Col_21  Wholesale and retail trade services repair ser...
20         NaN     Col_22                Transportation and storage services
21         NaN     Col_23                    Accommodation and food services
22         NaN     Col_24   Publishing audiovisual and broadcasting services
23         NaN     Col_25                        Telecommunications services
24         NaN     Col_26  Computer programming consultancy and related s...
25         NaN     Col_27                   Financial and insurance services
26         NaN     Col_28                               Real estate services
27         NaN     Col_29  Legal and accounting services services of head...
28         NaN     Col_30       Scientific research and development services
29         NaN     Col_31  Advertising and market research services other...
30         NaN     Col_32                Administrative and support services
31         NaN     Col_33  Public administration and defence services com...
32         NaN     Col_34                                 Education services
33         NaN     Col_35                              Human health services
34         NaN     Col_36                               Social work services
35         NaN     Col_37         Arts entertainment and recreation services
36         NaN     Col_38                                     Other services

In [86]:
encd_name = encd_name.drop(labels=['Unnamed: 0'], axis=1)

In [87]:
encd_name = encd_name.drop(labels=[0], axis=0)

In [88]:
encd_name

   Unnamed: 1                                   Encondig Columns
1       Col_3       Products of agriculture forestry and fishing
2       Col_4                               Mining and quarrying
3       Col_5       Food products beverages and tobacco products
4       Col_6      Textiles wearing apparel and leather products
5       Col_7      Wood and paper products and printing services
6       Col_8                Coke and refined petroleum products
7       Col_9                    Chemicals and chemical products
8      Col_10  Basic pharmaceutical products and pharmaceutic...
9      Col_11  Rubber and plastics products and other non-met...
10     Col_12  Basic metals and fabricated metal products exc...
11     Col_13           Computer electronic and optical products
12     Col_14                               Electrical equipment
13     Col_15                            Machinery and equipment
14     Col_16                                Transport equipment
15     Col_17  Furniture other manufactured goods repair and ...
16     Col_18         Electricity gas steam and air-conditioning
17     Col_19  Water supply sewerage waste management and rem...
18     Col_20               Constructions and construction works
19     Col_21  Wholesale and retail trade services repair ser...
20     Col_22                Transportation and storage services
21     Col_23                    Accommodation and food services
22     Col_24   Publishing audiovisual and broadcasting services
23     Col_25                        Telecommunications services
24     Col_26  Computer programming consultancy and related s...
25     Col_27                   Financial and insurance services
26     Col_28                               Real estate services
27     Col_29  Legal and accounting services services of head...
28     Col_30       Scientific research and development services
29     Col_31  Advertising and market research services other...
30     Col_32                Administrative and support services
31     Col_33  Public administration and defence services com...
32     Col_34                                 Education services
33     Col_35                              Human health services
34     Col_36                               Social work services
35     Col_37         Arts entertainment and recreation services
36     Col_38                                     Other services

In [89]:
#Export to CSV file
encd_name.to_csv(r"/Users/edgartome_1/IronHack/IronProjects/Project4/SQL/Encondig_Columns.csv", index=False)
encd_name

   Unnamed: 1                                   Encondig Columns
1       Col_3       Products of agriculture forestry and fishing
2       Col_4                               Mining and quarrying
3       Col_5       Food products beverages and tobacco products
4       Col_6      Textiles wearing apparel and leather products
5       Col_7      Wood and paper products and printing services
6       Col_8                Coke and refined petroleum products
7       Col_9                    Chemicals and chemical products
8      Col_10  Basic pharmaceutical products and pharmaceutic...
9      Col_11  Rubber and plastics products and other non-met...
10     Col_12  Basic metals and fabricated metal products exc...
11     Col_13           Computer electronic and optical products
12     Col_14                               Electrical equipment
13     Col_15                            Machinery and equipment
14     Col_16                                Transport equipment
15     Col_17  Furniture other manufactured goods repair and ...
16     Col_18         Electricity gas steam and air-conditioning
17     Col_19  Water supply sewerage waste management and rem...
18     Col_20               Constructions and construction works
19     Col_21  Wholesale and retail trade services repair ser...
20     Col_22                Transportation and storage services
21     Col_23                    Accommodation and food services
22     Col_24   Publishing audiovisual and broadcasting services
23     Col_25                        Telecommunications services
24     Col_26  Computer programming consultancy and related s...
25     Col_27                   Financial and insurance services
26     Col_28                               Real estate services
27     Col_29  Legal and accounting services services of head...
28     Col_30       Scientific research and development services
29     Col_31  Advertising and market research services other...
30     Col_32                Administrative and support services
31     Col_33  Public administration and defence services com...
32     Col_34                                 Education services
33     Col_35                              Human health services
34     Col_36                               Social work services
35     Col_37         Arts entertainment and recreation services
36     Col_38                                     Other services